### ISSUE TITLE
New Chapter for Georgetown, Guyana

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#101]
__Summary__
Maptime name: __MaptimeGuy__
Contact name: Guyana GIS UserGroup
Date submitted: 2015-06-04 16:52:51

- [x] Add GH admins to new team: 
- [x] Add Location (Georgetown, Guyana) to chapters.json and /chapters page.

__Additional tasks__
- [x] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by geografa** [comment]
All set here. We should email Guyana GIS UserGroup (dsurveyor@gmail.com) since they're not on GH yet.

**Comment by geobrando** [comment]
@geografa Did you send that email?

**Comment by geografa** [comment]
I thought I did but just sent and cc'ed you @geobrando
