### ISSUE TITLE
New Chapter for New Haven, Connecticut+

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#104]
__Summary__
Maptime name: __MaptimeNewHaven__
Contact name: Joseph a
Date submitted: 2015-06-07 20:58:04

- [x] Add GH admins to new team: 
- [x] Add Location (New Haven, Connecticut+) to chapters.json and /chapters page.

__Additional tasks__
- [x] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by redsteakraw** [comment]
The username for Joseph a is redsteakraw on github

**Comment by geobrando** [comment]
@redsteakraw Created a repo to manage your web page, which uses our starter template. Gave you write privileges.  

repo: https://github.com/maptime/newhaven
site: http://maptime.io/newhaven

You need to edit the [_config.yml](https://github.com/maptime/newhaven/blob/gh-pages/_config.yml) file in the repo.  Instructions are in the readme file.  We recommend securing a twitter handle and using it to promote your events and interact with your community. `@maptimeNewHaven` is 15 characters so it should fit in a twitter handle.  Or you could change the name of your chapter to maptimeNH or something else.  If you create one, you'll add it to the _config.yml

Let me know if you need help editing the config file or creating posts/events.  You're also free to scrap this starter template if you prefer to build a custom web page.

We'll also need to get you added to the map and list at http://maptime.io/chapters.  To do that, we will add your chapter to [chapters.json](https://github.com/maptime/maptime.github.io/blob/master/_data/chapters.json?short_path=672e323).  If you feel comfortable doing so, please edit the file with your chapter and submit a pull request.  If not, we can take care of that for you.

Please post any other questions you might have in #general channel on Slack.  I'm `@brandon` there.

Thanks!
