### ISSUE TITLE
New Chapter for State College, Pennsylvania, USA

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#105]
__Summary__
Maptime name: __MaptimeStateCollege__
Contact name: Marissa Defratti
Date submitted: 2015-06-07 21:15:38

- [ ] Add GH admins to new team: mdefratti, CarolynFish
- [ ] Add Location (State College, Pennsylvania, USA) to chapters.json and /chapters page.

__Additional tasks__
- [ ] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by mdefratti** [comment]
Can this issue be deleted in favor of my second request (MaptimePSU)? Sorry.

**Comment by geobrando** [comment]
No problem!
