### ISSUE TITLE
Cartography tutorial repo, please

### ISSUE THREAD

**Issue by danswick** [maptime/maptime-admin#110]
We have a bunch of ideas and notes from the Maptime summit cartography unconference session (what a string of words right there) that we would like to continue collaborating on. 

I put our notes and things into a repo with a wiki at https://github.com/danswick/cartography-anyone. Can someone just fork it into the Maptime group?

**Comment by danswick** [comment]
Learned that wikis don't survive forks, so just initiated a transfer request to @lyzidiamond. If this works, great! Otherwise, happy to keep this rolling in a new repo! 

:tractor: :corn: :cake:

**Comment by lyzidiamond** [comment]
@danswick can you reinitiate the transfer? It expired before I could get to it :blush:

**Comment by danswick** [comment]
should be reinitiated, @lyzidiamond
