### ISSUE TITLE
New Chapter for Columbus, GA, USA

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#112]
__Summary__
Maptime name: __MaptimeColsGA__
Contact name: Joseph D'Angelo
Date submitted: 2015-06-12 18:33:15

- [ ] Add GH admins to new team: ColumbusGAGIS
- [ ] Add Location (Columbus, GA, USA) to chapters.json and /chapters page.

__Additional tasks__
- [ ] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by geografa** [comment]
Repo is made here: https://github.com/maptime/columbus We may have to consider alternatives to the name given it's a popular city name. It's pretty easy to change at this stage.

**Comment by geobrando** [comment]
@geografa There was no github handle listed.  Sent an email to Joseph and asked if he had one, and if not to sign up for one.  Also sent him a Slack invite.

**Comment by geobrando** [comment]
Correction.  I see a handle above but it's an organization and not a individual user account.

**Comment by geobrando** [comment]
Slack invite and email may have failed due to copypasting of email address containing an apostrophe. Resent both.

**Comment by geografa** [comment]
reminder email sent

**Comment by geobrando** [comment]
@geografa I've sent a couple not sure if any have actually gotten through.  There's an apostrophe in the address and I think I read that gmail can't handle sending messages to these addresses.  You may have better luck with another client.  If we don't hear anything in a week I say we close.
