### ISSUE TITLE
CartoDB Pizza for 2015: System for reimbursement?

### ISSUE THREAD

**Issue by mtaylorlong** [maptime/maptime-admin#113]
MaptimeMSP is ready to take advantage of CartoDB's generous offer to cover Maptime pizza! The first time we did this, we used a google sheet and folder to add our info and receipt. Should we use this same process going forward, or is there another system CartoDB (@andrewxhill) would prefer for the rest of 2015? Thanks!

**Comment by andrewxhill** [comment]
Hey, adding @namessanti who is going to be getting it all set up this week, he can let you know when it is ready

**Comment by mtaylorlong** [comment]
Great – thanks Andrew!

**Comment by namessanti** [comment]
Hi all, Here is the form Maptime Meet-ups need to fill out in full for reimbursement:

<https://cartodb.wufoo.com/forms/maptime-sponsorship-form/>

(This is also all in the form, but want to make sure it gets distributed in your correspondences with organizers from the begining) It is very important that all Meet-ups know to please email me **1 week** before the schedules Meet-up with the name of the organizer, the city, and a link to the RSVP page of the meet up. This helps us keep track of where we're distributing funds and that everything looks good! Aside from that, there's some instructions on the form itself : )

Please let me know if you have any questions and enjoy the pizza. Yum!

**Comment by namessanti** [comment]
We are all set up from our end!

The process is as follows:
Maptime organizers need to email me at <santiago@cartodb.com> at least **1 week** prior to their Maptime Meet-up each month and include in the email:

1. The full name of the organizer
2. The Maptime Meet-up city
3. A link to the Meet-up RSVP website
4. Address where Meet-up will be held (If not on RSVP site)

From these emails I will approve and provide a link to a reimbursement form with additional instructions.
Please don't hesitate to email me with any questions and enjoy the pizza. Yum!

**Comment by geobrando** [comment]
Thanks, @namessanti!!

I believe that there have been a few chapters that have already held events and paid for pizza, assuming that your offer was already in effect.  Is CartoDB willing to extend this offer to these chapters and provide reimbursement?

**Comment by namessanti** [comment]
Of course! Let them know we have them covered and have them email me at <santiago@cartodb.com> as soon possible. Any Maptimes happening this week can also email me without the week notice. I'll share the form with them as soon as I hear from them.

**Comment by geobrando** [comment]
:+1: 

![pizza](http://i.giphy.com/eccZTdMZtUjfy.gif)

**Comment by namessanti** [comment]
Will you all here make sure everyone that needs this info gets it?

Thanks! 

That pizza looks delicious BTW

**Comment by geobrando** [comment]
@namessanti Already spread the word on our Slack channel!
