### ISSUE TITLE
New Chapter for Nantes, France

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#114]
__Summary__
Maptime name: __MaptimeNantes__
Contact name: Maptime Nantes
Date submitted: 2015-06-15 19:15:30

- [x] Add GH admins to new team: ThomasG77
- [x] Add Location (Nantes, France) to chapters.json and /chapters page.

__Additional tasks__
- [x] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by ThomasG77** [comment]
For location, the updated chapters.json is at https://github.com/ThomasG77/maptime.github.io/commit/98324b380dd7a858b6c75bcff5df6086faa40738

**Comment by geografa** [comment]
Hooray! Repo is here: https://github.com/maptime/nantes

Your website is here: http://maptime.io/nantes/

You can manage it, including customizing and adding posts and events using this repo, which you have push privileges to: https://github.com/maptime/nantes/. If you'd rather not use the template and want to create a site from scratch, you're welcome to.

We've added your chapter to `chapters.json`, which renders your chapter in the list on on the map at http://maptime.io/chapters/. When you're ready to start having event we can remove the "comingSoon": true tag.

I would recommend grabbing "MaptimeNantes" on twitter, after which you'd add it to `chapters.json` as well as the _config.yml in your repo.

Let us know if you think you'll have any need for a nantes@maptime.io email address.
And let me know if you have any questions either here or on Slack (@geografa).

**Comment by ThomasG77** [comment]
Thanks.
Everything is ready to update the site but I don't have the "right" permissions.

Doing `git push -u origin gh-pages` send back the following error:

```
ERROR: Permission to maptime/nantes.git denied to ThomasG77.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```
When I do `git remote -v`, nothing anormal
```
origin	git@github.com:maptime/nantes.git (fetch)
origin	git@github.com:maptime/nantes.git (push)
```

**Comment by geobrando** [comment]
Hi @ThomasG77.  You should have been given write access.  Changed permissions so you should be good to go now.

**Comment by ThomasG77** [comment]
So fast to answer ;)
Site published now using the template.
Need to announce first event (not created yet)
