### ISSUE TITLE
New Chapter for Silicon Valley (Palo Alto)

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#115]
__Summary__
Maptime name: __MaptimeSV__
Contact name: Sarah Levine, Stace Maples, David Medeiros, Jack Reed
Date submitted: 2015-06-16 03:31:25

- [x] Add GH admins to new team: https://github.com/mapninja, https://github.com/sml2198, https://github.com/mejackreed
- [x] Add Location (Silicon Valley (Palo Alto)) to chapters.json and /chapters page.

__Additional tasks__
- [x] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by geobrando** [comment]
Hey MaptimeSV!

* Your website has been created using our starter template and I edited the _config.yml.  Please feel free to make any changes you would like as the three organizers with gh accounts have been give write privileges.  Site is served [here](http://http://maptime.io/siliconvalley) and your repo is [here](https://github.com/maptime/siliconvalley).  You can also scrap that and build a site from scratch if you prefer.

* I added you to [chapters.json](https://github.com/maptime/siliconvalley) so your chapter is now rendered on the map and in the list at http://maptime.io/chapters.  If you need to make any changes or additions, please go ahead and let me know or make a pull request.

* I sent Slack invites to Stace and Sarah as I could find email addresses in their profiles.  If one of you could send me a message in Slack, either in #general or via PM with the other email addresses I can add Jack and David as well.  My name there is `@brandon`

Thanks and I'm happy to answer any other questions you may have.
