### ISSUE TITLE
New Chapter for Dar es Salaam, Tanzania

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#116]
__Summary__
Maptime name: __MaptimeTZ__
Contact name: Geoffrey Kateregga
Date submitted: 2015-06-17 10:06:23

- [x] Add GH admins to new team: Geoffrey Kateregga
- [x] Add Location (Dar es Salaam, Tanzania) to chapters.json and /chapters page.

__Additional tasks__
- [x] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by mapsam** [comment]
![danceparty](https://cloud.githubusercontent.com/assets/1943001/8215881/f044a4ca-14e7-11e5-9d83-8b12d41cd98e.gif)

**Comment by bethschechter** [comment]
Favorite issues comment this far. Well done, Mr. Matthews, well done!

**Comment by geografa** [comment]
@kateregga1 your new repo is herre: https://github.com/maptime/tanzania
and your site is live here: http://maptime.io/tanzania

It may take a moment to go live so please let me know if you don't see this shortly.

Also, I sent you an invitation to Slack. Check these details and let me know what questions you have or need help setting up the site!

**Comment by kateregga1** [comment]
@geografa thanks for setting up the site, Its already live. I have joined slack, all of this is cool staff, can't wait to show the people on the team for maptimeTZ how it all works.

**Comment by mapsam** [comment]
Congrats @kateregga1! Looking forward to hearing more from TZ.

**Comment by geografa** [comment]
:+1: :+1:

**Comment by kateregga1** [comment]
@geografa @mapsam How do I access @MaptimeTZ on twitter, do we create an account or it has already been created?

**Comment by geografa** [comment]
Yes, you'd need to create your own Twitter account. If MaptimeTZ is
available, I'd grab it soon.

On Sunday, June 21, 2015, Geoffrey Kateregga <notifications@github.com>
wrote:

> @geografa <https://github.com/geografa> @mapsam
> <https://github.com/mapsam> How do I access @MaptimeTZ on twitter, do we
> create an account or it has already been created?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maptime/maptime-admin/issues/116#issuecomment-113963421>
> .
>


-- 
Rafa Gutierrez
help@mapbox.com
