### ISSUE TITLE
New Chapter for Manteca, California

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#117]
__Summary__
Maptime name: __MaptimeManteca__
Contact name: Nathan
Date submitted: 2015-06-19 23:18:52

- [x] Add GH admins to new team: thisishap
- [ ] Add Location (Manteca, California) to chapters.json and /chapters page.

__Additional tasks__
- [x] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by geobrando** [comment]
@thisishap Created a repo to manage your web page, which uses our starter template. Gave you write privileges.  

repo: https://github.com/maptime/manteca
site: http://maptime.io/manteca

You need to edit the [_config.yml](https://github.com/maptime/manteca/blob/gh-pages/_config.yml) file in the repo.  Instructions are in the readme file.  We recommend securing a twitter handle and using it to promote your events and interact with your community. (e.g. `@maptimemanteca`). 

Let me know if you need help editing the config file or creating posts/events.  You're also free to scrap this starter template if you prefer to build a custom web page.

We'll also need to get you added to the map and list at http://maptime.io/chapters.  To do that, we will add your chapter to [chapters.json](https://github.com/maptime/maptime.github.io/blob/master/_data/chapters.json?short_path=672e323).  If you feel comfortable doing so, please edit the file with your chapter and submit a pull request.  If not, we can take care of that for you.

Please post any other questions you might have in #general channel on Slack.  I'm `@brandon` there.

Thanks!

**Comment by geobrando** [comment]
@thisishap Added you to chapters.json.  Let me know if you decide to get a personal and /or MaptimeManteca twitter account and we can add as well.
