### ISSUE TITLE
New Chapter for Charlotte, NC

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#119]
__Summary__
Maptime name: __CLT__
Contact name: David Chambers
Date submitted: 2015-06-28 14:22:19

- [x] Add GH admins to new team: dChambers14
- [ ] Add Location (Charlotte, NC) to chapters.json and /chapters page.

__Additional tasks__
- [x] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by geobrando** [comment]
Hey @dChambers14. Created a repo to manage your web page, which uses our starter template. Gave you write privileges.  

repo: https://github.com/maptime/charlotte
site: http://maptime.io/charlotte

You need to edit the [_config.yml](https://github.com/maptime/charlotte/blob/gh-pages/_config.yml) file in the repo.  Instructions are in the readme file.  We recommend securing a twitter handle and using it to promote your events and interact with your community. (e.g. `@maptimeCLT`). 

Let me know if you need help editing the config file or creating posts/events.  You're also free to scrap this starter template if you prefer to build a custom web page.

We'll also need to get you added to the map and list at http://maptime.io/chapters.  To do that, we will add your chapter to [chapters.json](https://github.com/maptime/maptime.github.io/blob/master/_data/chapters.json?short_path=672e323).  If you feel comfortable doing so, please edit the file with your chapter and submit a pull request.  If not, we can take care of that for you.  Just respond to this issue.

You should have received an invite to join our Slack, which is what we mainly use for communication between fellow organizers and Maptime leadership. Please post any other questions you might have about how to get started building MaptimeCLT in the #general channel on Slack.  I'm `@brandon` there.

Thanks!
