### ISSUE TITLE
New Chapter for Gotham

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#121]
__Summary__
Maptime name: __MaptimeGotham__
Contact name: John Doe
Date submitted: 2015-07-14 03:21:40

- [ ] Add GH admins to new team: jdoe78
- [ ] Add Location (Gotham) to chapters.json and /chapters page.

__Additional tasks__
- [ ] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by geobrando** [comment]
Test successful
