### ISSUE TITLE
New Chapter for Lisbon

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#124]
__Summary__
Maptime name: __MaptimeLisbon__
Contact name: Alexandra Dias
Date submitted: 2015-07-16 08:41:11

- [x] Add GH admins to new team: 
- [ ] Add Location (Lisbon) to chapters.json and /chapters page.

__Additional tasks__
- [x] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by geobrando** [comment]
Sent email requesting they sign up for a github account

**Comment by twink9** [comment]
Sorry for taking so long!  MaptimeLisbon checking in!

**Comment by geobrando** [comment]
Hello @twink9. I created a repo to manage your web page, which uses our starter template. I gave you write privileges.

repo: https://github.com/maptime/lisbon
site: http://maptime.io/lisbon

We recommend securing a twitter handle and using it to promote your events and interact with your community. (e.g. `@maptimelisbon`). If you choose to create a twitter account, please update the [_config.yml](https://github.com/maptime/lisbon/blob/gh-pages/_config.yml).  Let me know if you need help with this in addition to learning how to create posts/events on your site. You're also free to scrap this starter template if you prefer to build a custom web page.

We'll also need to get you added to the map and list at http://maptime.io/chapters. To do that, we will add your chapter to [chapters.json](https://github.com/maptime/maptime.github.io/blob/master/_data/chapters.json). If you feel comfortable doing so, please edit the file with your chapter information using the existing entries as an example and submit a pull request. If not, we can take care of that for you. Just respond to this issue.

You should have received an invite to join our Slack, which is what we primarily use for communication between fellow organizers and with Maptime leadership (also known as MaptimeHQ). Please post any other questions you might have about how to get started building MaptimeLisbon in the #general channel on Slack. I'm `@brandon` there.  If you have been able to recruit any additional organizers, please send me a direct message with their name, email address, and github name.

Thanks!
