### ISSUE TITLE
New Chapter for Tromso, Norway

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#125]
__Summary__
Maptime name: __MapTimeTOS__
Contact name: Annekatrien Debien
Date submitted: 2015-07-20 19:30:22

- [x] Add GH admins to new team: @Annekatrien
- [x] Add Location (Tromso, Norway) to chapters.json and /chapters page.

__Additional tasks__
- [x] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by geobrando** [comment]
Hey @Annekatrien. I created a repo to manage your web page which uses our starter template. I gave you write privileges.  

repo: https://github.com/maptime/tromso
site: http://maptime.io/tromso

I edited the  [_config.yml](https://github.com/maptime/tromso/blob/gh-pages/_config.yml) for you.  This is necessary to properly render your website.

Let me know if you need help creating posts/events.  You're also free to scrap this starter template if you prefer to build a custom web page.

I also added to the map and list at http://maptime.io/chapters by adding your chapter to [chapters.json](https://github.com/maptime/maptime.github.io/blob/master/_data/chapters.json?short_path=672e323).  If you need to update your info and feel comfortable doing so, please edit the file with your chapter and submit a pull request.  If not, we can take care of that for you.

You should have received an invite to join our Slack team, which is what we mainly use for communication between fellow organizers and Maptime leadership (MaptimeHQ). Please post any other questions you might have in the #general channel on Slack.  I'm `@brandon` there.

Thanks!
