### ISSUE TITLE
Slack invite/new organizer for Maptime Detroit

### ISSUE THREAD

**Issue by jmcbroom** [maptime/maptime-admin#126]
We have a new organizer, Chelsea Rozek. Her e-mail address is crozek@umich.edu

Thanks!

**Comment by geobrando** [comment]
Hey @jmcbroom. Sent her a Slack invite.  Updated chapters.json with her info (found her twitter account).  Also found her github account and invited her to the github org and your team. 

Welcome @ccrozek!  Feel free to reach out to me with any questions.  You can message or private message me on Slack.  My name is `@brandon`.

**Comment by ccrozek** [comment]
Nice to meet you, Brandon! Thanks for the invites!
