### ISSUE TITLE
New Chapter for South Western Florida

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#127]
__Summary__
Maptime name: __MaptimeSWF__
Contact name: Todd Barr
Date submitted: 2015-08-04 19:32:06

- [x] Add GH admins to new team: gistodd
- [x] Add Location (South Western Florida) to chapters.json and /chapters page.

__Additional tasks__
- [x] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by geobrando** [comment]
gistodd is not currently a valid github name. Email sent.

**Comment by georube** [comment]
Here I am...:)

**Comment by geografa** [comment]
@georube Hooray! Repo is here: https://github.com/maptime/sw-florida/

Your website is here: http://maptime.io/sw-florida/

You can manage it, including customizing and adding posts and events using this repo, which you have push privileges to: https://github.com/maptime/sw-florida/. If you'd rather not use the template and want to create a site from scratch, you're welcome to.

We still need to add your chapter to [chapters.json](https://github.com/maptime/maptime.github.io/blob/master/_data/chapters.json), which renders your chapter in the list on on the map at http://maptime.io/chapters/. When you're ready to start having event we can remove the `"comingSoon": true` tag.

I would recommend grabbing "MaptimeSWF" on twitter, after which you'd add it to chapters.json as well as the _config.yml in your repo. Let us know if you think you'll have any need for a sw-florida@maptime.io email address.

And let me know if you have any questions either here or on Slack (@geografa).
