### ISSUE TITLE
New Chapter for Nyeri,Kenya

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#129]
__Summary__
Maptime name: __Maptime254__
Contact name: Wanjohi Kibui
Date submitted: 2015-08-10 18:56:46

- [x] Add GH admins to new team: wanjohikibui
- [x] Add Location (Nyeri,Kenya) to chapters.json and /chapters page.

__Additional tasks__
- [x] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by geografa** [comment]
email sent re: new name,

**Comment by geografa** [comment]
@wanjohikibui - is it ok to change your repo name to MaptimeNyeri?

**Comment by wanjohikibui** [comment]
Yes.it's okay

**Comment by geobrando** [comment]
Hello @wanjohikibui. I created a repo to manage your web page, which uses our starter template. I gave you write privileges.

repo: https://github.com/maptime/nyeri
site: http://maptime.io/nyeri

I customized your site by editing the [_config.yml](https://github.com/maptime/nyeri/blob/gh-pages/_config.yml) file in the gh-pages branch.

We recommend securing a twitter handle and using it to promote your events and interact with your community (e.g. `@MaptimeNyeri`). If you choose to create a twitter account, please update the _config.yml.  Let me know if you need help learning how to create posts/events on your webpage. You're also free to scrap this starter template if you prefer to build a custom web page.

We'll also need to get you added to the map and list at http://maptime.io/chapters. To do that, we will add your chapter to [chapters.json](https://github.com/maptime/maptime.github.io/blob/master/_data/chapters.json). If you feel comfortable doing so, please edit the file with your chapter information using the existing entries as an example and submit a pull request. If not, we can take care of that for you. Just let us know.

You should have received an invite to join our Slack, which is what we primarily use for communication between fellow organizers and with Maptime leadership (also known as MaptimeHQ). Please post any other questions you might have about how to get started building MaptimeNyeri in the #general channel on Slack. I'm `@brandon` there.  If you have been able to recruit any additional organizers, please send me a direct message with their name, email address, and github name.

Thanks!
