### ISSUE TITLE
New Chapter for Copenhagen, Denmark

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#131]
__Summary__
Maptime name: __Maptime Copenhagen__
Contact name: Edoardo Neerhut
Date submitted: 2015-08-14 07:04:47

- [x] Add GH admins to new team: travel193, knikel, jesolem, sandrauddback
- [x] Add Location (Copenhagen, Denmark) to chapters.json and /chapters page.

__Additional tasks__
- [x] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by geografa** [comment]
Hello @travel193. I created a repo to manage your web page, which uses our starter template. I gave you write privileges.

repo: https://github.com/maptime/copenhagen
site: http://maptime.io/copenhagen

I edited the _config.yml file in the repo for you. We recommend securing a twitter handle and using it to promote your events and interact with your community. (e.g. @MaptimeCopenhagen). If you choose to create a twitter account, please update the _config.yml file or let me know so that I can edit it for you.

Let me know if you need help learning how to create posts/events on your site. You're also free to scrap this starter template if you prefer to build a custom web page.

We'll also need to get you added to the map and list at http://maptime.io/chapters. To do that, we will add your chapter to chapters.json. If you feel comfortable doing so, please edit the file with your chapter information using the existing entries as an example and submit a pull request. If not, we can take care of that for you. Just respond to this issue.

You should have received an invite to join our Slack, which is what we mainly use for communication between fellow organizers and Maptime leadership (also known as MaptimeHQ). Please post any other questions you might have about how to get started building MaptimeCopenhagenin the #general channel on Slack. I'm @geografa there.

Thanks!

**Comment by travel193** [comment]
Hi @geografa ,
Thanks for speedily setting up the Copenhagen repo.
I haven't seen any Slack invitations yet so if you haven't already it would be great to join the MapTime channel.
Looking forward to getting Copenhagen up and running!

**Comment by geografa** [comment]
Ooops. yes, left that out. Sent to mapillary account @travel193 - is that the one?

**Comment by travel193** [comment]
Fantastic. Thanks @geografa !
