### ISSUE TITLE
New Chapter for Baltimore, Maryland, USA

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#132]
__Summary__
Maptime name: __MaptimeBmore__
Contact name: Elliott Plack
Date submitted: 2015-08-15 01:47:12

- [x] Add GH admins to new team: talllguy
- [x] Add Location (Baltimore, Maryland, USA) to chapters.json and /chapters page.

__Additional tasks__
- [x] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by talllguy** [comment]
Hooray! :clap:

**Comment by geografa** [comment]
Hello @talllguy . I created a repo to manage your web page, which uses our starter template. I gave you write privileges.

repo: https://github.com/maptime/baltimore
site: http://maptime.io/baltimore

I edited the _config.yml file in the repo for you. We recommend securing a twitter handle and using it to promote your events and interact with your community. (e.g. @MaptimeBaltimore). If you choose to create a twitter account, please update the _config.yml file or let me know so that I can edit it for you.

Let me know if you need help learning how to create posts/events on your site. You're also free to scrap this starter template if you prefer to build a custom web page.

We'll also need to get you added to the map and list at http://maptime.io/chapters. To do that, we will add your chapter to chapters.json. If you feel comfortable doing so, please edit the file with your chapter information using the existing entries as an example and submit a pull request. If not, we can take care of that for you. Just respond to this issue.

You should have received an invite to join our Slack, which is what we mainly use for communication between fellow organizers and Maptime leadership (also known as MaptimeHQ). Please post any other questions you might have about how to get started building MaptimeBatimore in the #general channel on Slack. I'm @geografa there.

Thanks!

**Comment by talllguy** [comment]
@geografa thanks for getting this spun up!

### Twitter

I have secured https://twitter.com/maptimebmore on Twitter. I can add that to PR below as well.

### Website

Next I need to get the rest of the organizers on here and we can get to the website.

### Chapters

I'll fork and PR the entry into the chapters file. How does the `organizer` column work? I only see `[object Object]`. Here's a preview:

    {
      "type": "Feature",
      "properties": {
        "title": "MaptimeBmore",
        "location": "Baltimore, MD",
        "website": "",
        "twitter": "MaptimeBmore",
        "organizers": "",
        "comingSoon": "true",
        "meetup": "",
        "moreInfo": ""
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          -76.6107451915741,
          39.29085045233551
        ]
      }

### Slack

I haven't seen an invite in either email address I possess.

**Comment by geobrando** [comment]
@talllguy Excellent.  Despite what he posted, I think @geografa hadn't gotten to a new round of Slack invites yet.  I just sent you one. Sorry about that.

Check out the existing entries in the raw [chapters.json](https://raw.githubusercontent.com/maptime/maptime.github.io/master/_data/chapters.json) file which should help you out.

Also, do you know someone named Jade Clayton?  We have a note in our records that someone with that name was interested in starting Maptime Baltimore but I don't see any contact info for them.

**Comment by geografa** [comment]
oops! thanks @geobrando . Yep - I'll be more careful about sending these responses.

**Comment by talllguy** [comment]
@geobrando RE: Jade. Yes! We're working on this current effort in concert with a few others. She reached out to me a week ago. I'm handling some of the techie signups stuff and she's working on the logistics. But I assure you there will only be one MaptimeBmore :)

PS: Thanks for Slack

**Comment by talllguy** [comment]
Looks like @hoganmaps has the chapters bit under control https://github.com/maptime/maptime.github.io/pull/216
