### ISSUE TITLE
New Chapter for Cambridge, United Kingdom

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#133]
__Summary__
Maptime name: __MaptimeCAM__
Contact name: Abigail Walton
Date submitted: 2015-08-15 09:31:46

- [x] Add GH admins to new team: Abigail Walton - @abuwalton
- [x] Add Location (Cambridge, United Kingdom) to chapters.json and /chapters page.

__Additional tasks__
- [x] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by geografa** [comment]
Hello @ahmednosman. I created a repo to manage your web page, which uses our starter template. I gave you write privileges.

repo: https://github.com/maptime/cambridge
site: http://maptime.io/cambridge

I edited the _config.yml file in the repo for you. We recommend securing a twitter handle and using it to promote your events and interact with your community. (e.g. @MaptimeCambridge). If you choose to create a twitter account, please update the _config.yml file or let me know so that I can edit it for you.

Let me know if you need help learning how to create posts/events on your site. You're also free to scrap this starter template if you prefer to build a custom web page.

We'll also need to get you added to the map and list at http://maptime.io/chapters. To do that, we will add your chapter to chapters.json. If you feel comfortable doing so, please edit the file with your chapter information using the existing entries as an example and submit a pull request. If not, we can take care of that for you. Just respond to this issue.

You should have received an invite to join our Slack, which is what we mainly use for communication between fellow organizers and Maptime leadership (also known as MaptimeHQ). Please post any other questions you might have about how to get started building MaptimeCambridge in the #general channel on Slack. I'm @geografa there.

Thanks!

**Comment by geobrando** [comment]
@geografa Edited above to correctly ping Abigail
