### ISSUE TITLE
New Chapter for Durham, North East England, UK 

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#134]
__Summary__
Maptime name: __MaptimeDurham__
Contact name: Gregory Marler 
Date submitted: 2015-08-20 10:54:50

- [x] Add GH admins to new team: nomoregrapes 
- [x] Add Location (Durham, North East England, UK ) to chapters.json and /chapters page.

__Additional tasks__
- [x] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by almccon** [comment]
I'd suggest picking a name like MaptimeDurham, since NE could refer to many different places.

**Comment by nomoregrapes** [comment]
A lot of groups round here end "North East" and my thinking was that could make it stronger, a lot of people commute between the 3 cities. Still, I think you're right Alan. I was thinking it might be good to rotate around the cities with MaptimeNE, but I could later create MaptimeNewcastle and MaptimeSunderland and have each group meet every 3 months rather than every month.

Do I need to change the request somehow to MaptimeDurham, or will that be done as a result of this comment?

**Comment by nomoregrapes** [comment]
I've created social media accounts with the preferred name.
* https://twitter.com/MaptimeDurham
* https://www.facebook.com/MaptimeDurham

To motivate me to do this I also booked in space for a first event at a local pub/cafe on the 2nd September. I'm now hoping that isn't too short to make interested people aware!

**Comment by geobrando** [comment]
Great job @nomoregrapes!! Durham is not an uncommon city name in the US, with the most well known being Durham, North Carolina.  We actually had someone express interest in a Maptime Durham, NC a while back but nothing came of it.  But we can cross that bridge when we come to it.  You're the first MaptimeDurham!  If you want you could always go ahead and change to MaptimeDurhamUK, but that's totally up to you.

I think it's ok to have any event so soon. If anything, you'll attract the hardcore people and may be able to recruit them as fellow organizers.

We'll get you set up with a repo shortly, but I went ahead and sent a Slack invite to the email address we have for you on file.

**Comment by nomoregrapes** [comment]
Spending my lunchtime on promoting the first event, I thought what I could do to help with the MaptimeHQ setup.

I've created a gist that could be copied into the chapters.geojson: https://gist.github.com/nomoregrapes/a68aa5eca4bb6704e3e8

I'm new to creating/editing pages on Github so I'll leave that for now. I think I'll pick it up easy enough when the starter template is in place.
