### ISSUE TITLE
Add Baltimore Organizers to Maptime GH Organization

### ISSUE THREAD

**Issue by talllguy** [maptime/maptime-admin#135]
Greetings. Now that Baltimore is mostly online (#132), we need to get the fellow organizers on the github organization, Baltimore team (for working on the website and etc).

[Here is a list of organizers with their GitHub handles](
https://github.com/maptimebmore/set-up/issues/3#issue-101131583). I am already added.

Thanks!

**Comment by geobrando** [comment]
Done.  Feel free to add those not already list to [chapters.json](https://github.com/maptime/maptime.github.io/blob/master/_data/chapters.json).
