### ISSUE TITLE
New Chapter for Champaign-Urbana, Illinois, USA

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#136]
__Summary__
Maptime name: __MaptimeUIUC__
Contact name: Edison Orellana
Date submitted: 2015-08-21 18:30:49

- [x] Add GH admins to new team: annuit02
- [ ] Add Location (Champaign-Urbana, Illinois, USA) to chapters.json and /chapters page.

__Additional tasks__
- [x] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by geografa** [comment]
@annuit02

Hooray! Repo is here: https://github.com/maptime/champaign-urbana/

Your website is here: http://maptime.io/champaign-urbana/

You can manage it, including customizing and adding posts and events using this repo, which you have push privileges to: https://github.com/maptime/champaign-urbana/. If you'd rather not use the template and want to create a site from scratch, you're welcome to.

We still need to add your chapter to [chapters.json](https://github.com/maptime/maptime.github.io/blob/master/_data/chapters.json), which renders your chapter in the list on on the map at http://maptime.io/chapters/. When you're ready to start having event we can remove the `"comingSoon": true` tag

I would recommend grabbing "MaptimeUIUC" on twitter, after which you'd add it to chapters.json as well as the _config.yml in your repo.

Let us know if you think you'll have any need for a champaign-urbana@maptime.io email address.
And let me know if you have any questions either here or on Slack (@geografa)

**Comment by edisondotme** [comment]
Thanks! We're looking forward to start having events. The maptime chapter
is currently being run by a local club on campus called the urban and
geographic information systems group http://www.ugisgroup.org/ I was
thinking recently about getting our name changed to "MaptimeCU" instead of
"MaptimeUIUC" so that we could match everyone else on maptime and market to
our city as a whole instead of just our University. Can we process that
change?

Thanks,

-EO

**Comment by geobrando** [comment]
Hey @annuit02.  Made the change in your _config.yml and added you to chapters.json using the new chapter name.  Let us know if you have any additional organizers you would like for us to add to Slack and to the website.

**Comment by edisondotme** [comment]
Sure, there are two members to add to slack.

Clayton Locher - clocher2@illinois.edu
Jacob Jasek - jjasek2@illinois.edu

**Comment by almccon** [comment]
Invites sent.
