### ISSUE TITLE
Get stickers on Zazzle or something equivalent

### ISSUE THREAD

**Issue by bethschechter** [maptime/maptime-admin#138]
that way people can order stickers as needed, and we don't need to worry about fulfillment. yay!

**Comment by almccon** [comment]
For anybody who wants to make their own stickers, there's an .ai file and a PDF in this folder: https://github.com/maptime/maptime-logo/tree/gh-pages/illustrator

**Comment by almccon** [comment]
Good enough! https://www.stickermule.com/user/1070708614/stickers :shipit:
