### ISSUE TITLE
New Chapter for Donostia-San Sebastian, País Vasco

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#139]
**Summary**
Maptime name: **Maptime Moviles**
Contact name: Asier
Date submitted: 2015-09-16 07:19:06
- [ ] Add GH admins to new team: no
- [ ] Add Location (Donostia-San Sebastian, País Vasco) to chapters.json and /chapters page.

**Additional tasks**
- [ ] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by almccon** [comment]
Is this chapter named "Maptime Moviles" because it plans to hold meetings in multiple cities? In that case, just use the region name. Or does "Moviles" mean something else locally?

We need to make sure they name it something more specific.

**Comment by geobrando** [comment]
No github username was supplied so I sent an email to the addresses on file for this issue as well as #140 and asked for them to register and respond to the chapter name issue.

**Comment by geobrando** [comment]
Sending one more email.  If no response in a week or so I will close.
