### ISSUE TITLE
New Chapter for Donostia, Euskal herria

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#140]
**Summary**
Maptime name: **maptime**
Contact name: Aritz
Date submitted: 2015-09-18 11:52:35
- [ ] Add GH admins to new team: no
- [ ] Add Location (Donostia, Euskal herria) to chapters.json and /chapters page.

**Additional tasks**
- [ ] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by almccon** [comment]
Dupe of #139. Still doesn't have an appropriate name.

**Comment by geografa** [comment]
close in favor of #139
