### ISSUE TITLE
New Chapter for Gothenburg, Sweden 

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#141]
**Summary**
Maptime name: **MaptimeGBG**
Contact name: Semone Kallin Clarke
Date submitted: 2015-09-18 16:03:19
- [x] Add GH admins to new team: semone
- [x] Add Location (Gothenburg, Sweden ) to chapters.json and /chapters page.

**Additional tasks**
- [x] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by geografa** [comment]
@semone
Hooray! Repo is here: https://github.com/maptime/gothenburg/

Your website is here: http://maptime.io/gothenburg/

You can manage it, including customizing and adding posts and events using this repo, which you have push privileges to: https://github.com/maptime/gothenburg/. If you'd rather not use the template and want to create a site from scratch, you're welcome to.

We still need to add your chapter to [chapter.json](https://github.com/maptime/maptime.github.io/blob/master/_data/chapters.json), which renders your chapter in the list on on the map at http://maptime.io/chapters/. When you're ready to start having event we can remove the `"comingSoon": true` tag.

I would recommend grabbing "MaptimeGBG" on twitter, after which you'd add it to chapters.json as well as the _config.yml in your repo.

Let us know if you think you'll have any need for a gothenburg@maptime.io email address.
And let me know if you have any questions either here or on Slack (@geografa).

**Comment by geobrando** [comment]
Hey @semone.  You're added to chapters.json which means you chapter is also now visible on our website.  I also have now added you to Slack.  Feel free to reach out with any questions there by mentioning `@geografa` or myself (`@geobrando`)
