### ISSUE TITLE
New Chapter for Chengdu,Sichuan,China

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#146]
**Summary**
Maptime name: **defsdf**
Contact name: cvxvc
Date submitted: 2015-10-09 16:09:24
- [ ] Add GH admins to new team: no
- [ ] Add Location (Chengdu,Sichuan,China) to chapters.json and /chapters page.

**Additional tasks**
- [ ] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by almccon** [comment]
seems legit

**Comment by geobrando** [comment]
haha
