### ISSUE TITLE
MaptimeBoulder website request

### ISSUE THREAD

**Issue by jenningsanderson** [maptime/maptime-admin#148]
Hi all,
I'd like to formalize a github webpage for MaptimeBoulder, beyond our Meetup page. Can I please request a repository for maptime.io/boulder? Thanks!

**Comment by geobrando** [comment]
Hey @jenningsanderson.  You're good to go

https://github.com/maptime/boulder
http://maptime.io/boulder/

I also updated [chapters.json](https://github.com/maptime/maptime.github.io/blob/master/_data/chapters.json), adding these urls as well as adding you to the organizer list so everything is properly rendered at http://maptime.io/chapters.

Let me know if you need any help creating posts/events.
