### ISSUE TITLE
New Chapter for San Antonio, TX

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#149]
**Summary**
Maptime name: **MaptimeSATX**
Contact name: Emily Bowe
Date submitted: 2015-10-16 16:13:41
- [x] Add GH admins to new team: https://github.com/emilyrbowe
- [ ] Add Location (San Antonio, TX) to chapters.json and /chapters page.

**Additional tasks**
- [x] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by geobrando** [comment]
Hello @emilyrbowe. I created a repo to manage your web page, which uses our starter template. I gave you write privileges.

repo: https://github.com/maptime/sanantonio
site: http://maptime.io/sanantonio

We recommend securing a twitter handle and using it to promote your events and interact with your community. (e.g. `@MaptimeSATX`). If you choose to create a twitter account, please update the [_config.yml](https://github.com/maptime/sanantonio/gh-pages/_config.yml).  Let me know if you need help with this in addition to learning how to create posts/events on your site. You're also free to scrap this starter template if you prefer to build a custom web page.

We'll also need to get you added to the map and list at http://maptime.io/chapters. To do that, we will add your chapter to [chapters.json](https://github.com/maptime/maptime.github.io/blob/master/_data/chapters.json). If you feel comfortable doing so, please edit the file with your chapter information using the existing entries as an example and submit a pull request. If not, we can take care of that for you. Just respond to this issue.

You should have received an invite to join our Slack, which is what we primarily use for communication between fellow organizers and with Maptime leadership (also known as MaptimeHQ). Please post any other questions you might have about how to get started building MaptimeSATX in the #general channel on Slack. I'm `@brandon` there.  If you have been able to recruit any additional organizers, please send me a direct message with their name, email address, and github name.

Thanks!

**Comment by emilyrbowe** [comment]
Thanks for the message, @geobrando! 

I'll start getting on these tasks and will let you know if I run into any issues.

**Comment by lukewhyte** [comment]
Hi @emilyrbowe! 

I just moved to San Antonio and was hoping to get a Maptime chapter up and off the ground here. I see that you'd started down this path previously. Is there a currently active chapter? If not, are you still interested in cooking something up?

**Comment by emilyrbowe** [comment]
@lukewhyte I'd had the plan on hold and it was a 2017 resolution to get it up and running. Would love to meet up to chat maptime! Emailing you now.

**Comment by emilyrbowe** [comment]
Hey guys, can we get @lukewhyte added to the Maptime San Antonio team? @geobrando @geografa Thank you!
