### ISSUE TITLE
New Chapter for Eugene, Oregon, USA

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#150]
**Summary**
Maptime name: **MaptimeEUG**
Contact name: Christine Grummon
Date submitted: 2015-10-17 15:04:47
- [x] Add GH admins to new team: grummonc
- [x] Add Location (Eugene, Oregon, USA) to chapters.json and /chapters page.

**Additional tasks**
- [x] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by lyzidiamond** [comment]
This brings me such joy.

**Comment by geobrando** [comment]
Hello @grummonc. I created a repo to manage your web page, which uses our starter template. I gave you write privileges.

repo: https://github.com/maptime/eugene
site: http://maptime.io/eugene

We recommend securing a twitter handle and using it to promote your events and interact with your community. (e.g. `@MaptimeEUG`). If you choose to create a twitter account, please update the  [_config.yml](https://github.com/maptime/eugene/gh-pages/_config.yml).  Let me know if you need help learning how to create posts/events on your site. You're also free to scrap this starter template if you prefer to build a custom web page.

We'll also need to get you added to the map and list at http://maptime.io/chapters. To do that, we will add your chapter to [chapters.json](https://github.com/maptime/maptime.github.io/blob/master/_data/chapters.json). If you feel comfortable doing so, please edit the file with your chapter information using the existing entries as an example and submit a pull request. If not, we can take care of that for you. Just respond to this issue.

You should have received an invite to join our Slack, which is what we primarily use for communication between fellow organizers and with Maptime leadership (also known as MaptimeHQ). Please post any other questions you might have about how to get started building MaptimeEUG in the #general channel on Slack. I'm `@brandon` there.  If you have been able to recruit any additional organizers, please send me a direct message with their name, email address, and github name.

Thanks!
