### ISSUE TITLE
New Chapter for jordan

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#151]
**Summary**
Maptime name: **mymaptime**
Contact name: khitam
Date submitted: 2015-10-21 15:55:55
- [ ] Add GH admins to new team: 
- [ ] Add Location (jordan) to chapters.json and /chapters page.

**Additional tasks**
- [ ] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by almccon** [comment]
Cool! I'd recommend a name like MaptimeJordan or MaptimeAmman.

**Comment by geobrando** [comment]
Removed email address in ticket for privacy reasons
Sent an email address asking that they sign up for a github account

**Comment by geografa** [comment]
did we get a response?

**Comment by geobrando** [comment]
@geografa I have not

**Comment by geobrando** [comment]
Sent one last email
