### ISSUE TITLE
New Chapter for İzmir, Turkey

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#153]
**Summary**
Maptime name: **Maptimeİzmir**
Contact name: Melis
Date submitted: 2015-11-07 17:28:14
- [ ] Add GH admins to new team: 
- [ ] Add Location (İzmir, Turkey) to chapters.json and /chapters page.

**Additional tasks**
- [x] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by geobrando** [comment]
- Slack invite not sent to correct email address. Resent.
- Sent an email asking to respond to this issue

**Comment by geobrando** [comment]
Resent Slack invite and followed up with one final email.
