### ISSUE TITLE
New Chapter for UDSM, Dar es Salaam, tz

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#154]
**Summary**
Maptime name: **Maptime UDSM**
Contact name: calistevance
Date submitted: 2015-11-10 09:28:40
- [x] Add GH admins to new team: kateregga1, innosaint
- [x] Add Location (UDSM, Dar es Salaam, tz) to chapters.json and /chapters page.

**Additional tasks**
- [ ] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by almccon** [comment]
So this is https://en.wikipedia.org/wiki/University_of_Dar_es_Salaam I guess? And #155 is https://en.wikipedia.org/wiki/Ardhi_University? Are we sure that these two universities in the same city both need their own Maptime chapters, when we already have https://github.com/maptime/tanzania representing Dar es Salaam? @kateregga1

**Comment by geografa** [comment]
we're here at #155
