### ISSUE TITLE
New Chapter for Nîmes, Gard, France

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#157]
**Summary**
Maptime name: **MaptimeNîmes**
Contact name: Alexandre Simonet
Date submitted: 2015-12-07 00:07:27
- [x] Add GH admins to new team: Labo2
- [x] Add Location (Nîmes, Gard, France) to chapters.json and /chapters page.

**Additional tasks**
- [x] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by geobrando** [comment]
Hello @Labo2. I created a repo to manage your web page, which uses our starter template. I gave you write privileges.

repo: https://github.com/maptime/nimes
site: http://maptime.io/nimes

Please customize your site by editing the [_config.yml](https://github.com/maptime/nimes/blob/gh-pages/_config.yml) file in the gh-pages branch. I am happy to assist with this if help is needed. We recommend securing a twitter handle and using it to promote your events and interact with your community. (e.g. `@MaptimeNimes`). If you choose to create a twitter account, please update the _config.yml.  Let me know if you need help learning how to create posts/events on your site. You're also free to scrap this starter template if you prefer to build a custom web page.

We'll also need to get you added to the map and list at http://maptime.io/chapters. To do that, we will add your chapter to [chapters.json](https://github.com/maptime/maptime.github.io/blob/master/_data/chapters.json). If you feel comfortable doing so, please edit the file with your chapter information using the existing entries as an example and submit a pull request. If not, we can take care of that for you. Just respond to this issue.

You should have received an invite to join our Slack, which is what we primarily use for communication between fellow organizers and with Maptime leadership (also known as MaptimeHQ). Please post any other questions you might have about how to get started building MaptimeNimes in the #general channel on Slack. I'm `@brandon` there.  If you have been able to recruit any additional organizers, please send me a direct message with their name, email address, and github name.

Thanks!

**Comment by almccon** [comment]
:fr: :100: :zap:

**Comment by volvac** [comment]
Hello Brandon,
Thanks for your help.
I tried to change my website via _config.yml but i made a mystake...
Can you help me, please ?
Thanks.
Alex

**Comment by geobrando** [comment]
@volvac Is this account the one you would like to use for maptime or @Labo2?

**Comment by volvac** [comment]
Oups !!! it's Labo2

**Comment by geobrando** [comment]
@Labo2 I fixed the link above so it will correctly send you to the config.yml.  But I went ahead and edited it for you.

Feel free to try and update chapters.json with your info.  Or if you prefer we can update for you as well.
