### ISSUE TITLE
New Chapter for Riverside, California, USA

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#158]
**Summary**
Maptime name: **MaptimeIE**
Contact name: Clinton Dow
Date submitted: 2015-12-14 19:21:27
- [x] Add GH admins to new team: data-navigator
- [x] Add Location (Riverside, California, USA) to chapters.json and /chapters page.

**Additional tasks**
- [x] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by almccon** [comment]
Neat! However, @data-navigator, I'd suggest a different name. The abbreviation IE for Inland Empire probably means a lot of different things in other places. For example, it's also the country code for Ireland.

I suggest MaptimeRiverside, which is more clear, and which can still attracted attendees from the greater Inland Empire area.

**Comment by data-navigator** [comment]
Okay, that's fair. I'm fine with MaptimeRiverside!

**Comment by geografa** [comment]
:+1:

**Comment by geobrando** [comment]
Hello @data-navigator . I created a repo to manage your web page, which uses our starter template. I gave you write privileges.

repo: https://github.com/maptime/riverside
site: http://maptime.io/riverside

Please customize your site by editing the [_config.yml](https://github.com/maptime/riverside/gh-pages/_config.yml) file in the gh-pages branch. I am happy to assist with this if help is needed. We recommend securing a twitter handle and using it to promote your events and interact with your community. (e.g. `@MaptimeRiverside`). If you choose to create a twitter account, please update the _config.yml.  Let me know if you need help learning how to create posts/events on your site. You're also free to scrap this starter template if you prefer to build a custom web page.

We'll also need to get you added to the map and list at http://maptime.io/chapters. To do that, we will add your chapter to [chapters.json](https://github.com/maptime/maptime.github.io/blob/master/_data/chapters.json). If you feel comfortable doing so, please edit the file with your chapter information using the existing entries as an example and submit a pull request. If not, we can take care of that for you. Just respond to this issue.

You should have received an invite to join our Slack, which is what we primarily use for communication between fellow organizers and with Maptime leadership (also known as MaptimeHQ). Please post any other questions you might have about how to get started building MaptimeIE in the #general channel on Slack. I'm `@brandon` there.  If you have been able to recruit any additional organizers, please send me a direct message with their name, email address, and github name.

Thanks!

**Comment by almccon** [comment]
:keycap_ten: Thanks @geobrando!

**Comment by data-navigator** [comment]
Thanks guys, I'm just in the middle of finishing up a release at work so quite busy for a couple weeks, but I've got all this on my to-do list. :)
