### ISSUE TITLE
New Chapter for Porto

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#159]
**Summary**
Maptime name: **Porto**
Contact name: João
Date submitted: 2015-12-18 17:35:02
- [ ] Add GH admins to new team: 
- [ ] Add Location (Porto) to chapters.json and /chapters page.

**Additional tasks**
- [ ] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by geobrando** [comment]
No github username or email address given. Closing.
