### ISSUE TITLE
New Starter Site for Maptime Southampton

### ISSUE THREAD

**Issue by charleyglynn** [maptime/maptime-admin#161]
@geografa Could you please set me up a new starter site for Maptime Southampton (Twitter: @maptimeSOTON)

Cheers

**Comment by geobrando** [comment]
Hello @charleyglynn. I created a repo to manage your web page, which uses our starter template. I gave you write privileges.

repo: https://github.com/maptime/southapmton
site: http://maptime.io/southampton

Please customize your site by editing the [_config.yml](https://github.com/maptime/southampton/gh-pages/_config.yml) file in the gh-pages branch. I am happy to assist with this if help is needed. Let me know if you need help learning how to create posts/events on your site.

I also added the website url to [chapters.json](https://github.com/maptime/maptime.github.io/blob/master/_data/chapters.json) which means it will render at http://maptime.io/chapters

**Comment by almccon** [comment]
:gb: :shell: :fish:

**Comment by charleyglynn** [comment]
Awesome! Thanks so much!! C
