### ISSUE TITLE
Organizer change MaptimeAMS

### ISSUE THREAD

**Issue by NieneB** [maptime/maptime-admin#162]
Maptime Amsterdam changed organizers. Could the name of Bert Spaan be changed to Niene Boeijen in the Maptime Chapters? ( Twitter @BNiene ) 
Thanks!

**Comment by geobrando** [comment]
Hi @NieneB.  Sorry to lose Bert, but welcome to you!  You should be good to go.

**Comment by geobrando** [comment]
@NieneB Are you on our Slack?  If not, please post your email address and I'll send you an invite.  If you prefer not to post that here, send me an email to dc@maptime.io and I'll invite you.

**Comment by almccon** [comment]
I added @NieneB to slack (same username there).

**Comment by NieneB** [comment]
Ha Thanks! I'm happy to join :)
