### ISSUE TITLE
New Chapter for Kiev, Ukraine

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#163]
**Summary**
Maptime name: **Lidia_map**
Contact name: cartographer
Date submitted: 2016-01-12 12:51:41
- [ ] Add GH admins to new team: 
- [ ] Add Location (Kiev, Ukraine) to chapters.json and /chapters page.

**Additional tasks**
- [ ] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by almccon** [comment]
Bummer, I was so excited to see MaptimeKiev, but it looks like there's no real lead here. I can't find any user named `lidia_map`, and @cartographer doesn't seem like the actual handle of someone in Kiev. Oh well.
