### ISSUE TITLE
New Chapter for Bogota, Colombia

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#164]
**Summary**
Maptime name: **MaptimeCO**
Contact name: Andres Gomez Casanova
Date submitted: 2016-01-15 02:51:54
- [x] Add GH admins to new team: angoca
- [x] Add Location (Bogota, Colombia) to chapters.json and /chapters page.

**Additional tasks**
- [x] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by geobrando** [comment]
Hello @angoca.  Thank you for you interest.  Would you be okay if we rename "MaptimeBogota"?

**Comment by angoca** [comment]
Ok, no problem. Anyway, I will be working more on Bogota, instead of the whole country. The name could also be MaptimeBog, but it is up to you to decide the most according name. Thank you.

**Comment by geobrando** [comment]
Hello @angoca. I created a repo to manage your web page, which uses our starter template. I gave you write privileges.

repo: https://github.com/maptime/bogota
site: http://maptime.io/bogota

I customized your site by editing the [_config.yml](https://github.com/maptime/bogota/blob/gh-pages/_config.yml) file. Feel free to further customize. I am happy to assist with this if help is needed.

We recommend securing a twitter handle and using it to promote your events and interact with your community. (e.g. `@MaptimeBogota`). If you choose to create a twitter account, please update the _config.yml.  Let me know if you need help learning how to create posts/events on your site. You're also free to scrap this starter template if you prefer to build a custom web page.

I'm adding your information to [chapters.json](https://github.com/maptime/maptime.github.io/blob/master/_data/chapters.json) which will add you to the map and list at http://maptime.io/chapters. If you feel comfortable doing so, please submit a pull request for any info that I may have missed.  If you don't, just respond to this issue and I can take care of it for you.

You should have received an invite to join our Slack, which is what we primarily use for communication between fellow organizers and with Maptime leadership (also known as MaptimeHQ). Please post any other questions you might have about how to get started building MaptimeBogota in the #general channel on Slack. I'm `@brandon` there.  If you have been able to recruit any additional organizers, please send me a direct message with their name, email address, and github name.

Thanks!
