### ISSUE TITLE
New Chapter for Utrecht, Netherlands

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#165]
**Summary**
Maptime name: **MaptimeUtrecht**
Contact name: Edward Mac Gillavry
Date submitted: 2016-01-15 11:58:26
- [x] Add GH admins to new team: emacgillavry, hpfast, sabeare
- [x] Add Location (Utrecht, Netherlands) to chapters.json and /chapters page.

**Additional tasks**
- [x] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by geobrando** [comment]
Hello @emacgillavry. I created a repo to manage your web page, which uses our starter template. I gave you write privileges.

repo: https://github.com/maptime/utrecht
site: http://maptime.io/utrecht

Please customize your site by editing the [_config.yml](https://github.com/maptime/utrecht/blob/gh-pages/_config.yml) file in the gh-pages branch. I am happy to assist with this if help is needed. We recommend securing a twitter handle and using it to promote your events and interact with your community. (e.g. `@MaptimeUtrecht`). If you choose to create a twitter account, please update the _config.yml.  Let me know if you need help learning how to create posts/events on your site. You're also free to scrap this starter template if you prefer to build a custom web page.

We'll also need to get you added to the map and list at http://maptime.io/chapters. To do that, we will add your chapter to [chapters.json](https://github.com/maptime/maptime.github.io/blob/master/_data/chapters.json). If you feel comfortable doing so, please edit the file with your chapter information using the existing entries as an example and submit a pull request. If not, we can take care of that for you. Just respond to this issue.

You should have received an invite to join our Slack, which is what we primarily use for communication between fellow organizers and with Maptime leadership (also known as MaptimeHQ). Please post any other questions you might have about how to get started building Maptime<chapterName> in the #general channel on Slack. I'm `@brandon` there.  Please send me a direct message with the email address of your other organizers and I can send them invites as well.

Thanks!

**Comment by emacgillavry** [comment]
Hi Brandon,

Thnx for setting up a repo for us. We'll start customisation of the website
shortly and securing the Twitter account.

Cheers,

Edward
Op 25 jan. 2016 05:20 schreef "Brandon Knight" notifications@github.com:
