### ISSUE TITLE
New Chapter for Portland, Maine

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#166]
**Summary**
Maptime name: **MaptimeMe**
Contact name: Michael Lodge-Paolini
Date submitted: 2016-01-16 16:56:00
- [x] Add GH admins to new team: maikuru
- [x] Add Location (Portland, Maine) to chapters.json and /chapters page.

**Additional tasks**
- [x] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by geobrando** [comment]
Hi @maikuru.  I know that @nickkauf expressed interest in rebooting MaptimeME some time ago.  Are you working with him or going alone? We'll need to add you to [chapters.json](https://github.com/maptime/maptime.github.io/blob/ec56aee67769130164120d3946fa3687cb43a30b/_data/chapters.json).  Do you have any interest in using our starter template code to host a website?

repo: https://github.com/maptime/starter
site: http://maptime.io/starter

**Comment by NickKauf** [comment]
Hey Michael! this is good, I had some interest in ressurecting the maine group after visiting the summmit this summer and got connected to some of the official resources, was planning to come to the lightning talks you scheduled today and see about relaying all that info, as I always wanted to be involved in maptime-maine but am a carto-geo newbie and couldnt find any others who wanted to organize over the summer. will try to connect today

**Comment by NickKauf** [comment]
@geobrando can you add Michael @maikuru as the lead chapter admin for maptimeME and get him a slack invite etc.? I'm still planning to be involved in the meetup but he's ready to take the lead.

**Comment by geobrando** [comment]
@NickKauf Done!

@maikuru Let me know if you want to use the starter repo.  Currently http://maptime.io/maine is displaying the custom site the previous organizer created.

Also, I'm editing chapters.json with your info.  Feel free to add anything that I missed. I added the name of the other organizer on the meetup page.  If Jesse needs a Slack invite I can send one.  Just send me a private message with the email address through Slack `@brandon`

https://github.com/maptime/maptime.github.io/blob/master/_data/chapters.json

The twitter has not been used in a while. Either of you have access to it?

https://twitter.com/maptimeme
