### ISSUE TITLE
New Chapter for Online

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#167]
**Summary**
Maptime name: **MaptimeWeb**
Contact name: Annekatrien
Date submitted: 2016-01-18 09:52:01
- [ ] Add GH admins to new team: Annekatrien
- [ ] Add Location (Online) to chapters.json and /chapters page.

**Additional tasks**
- [ ] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by geobrando** [comment]
@annekatrien As we talked about before, try to connect with some of the others who are interested in creating maptime videos or online tutorials.
