### ISSUE TITLE
New Chapter for San Diego

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#168]
**Summary**
Maptime name: **MaptimeSD**
Contact name: Rob C.
Date submitted: 2016-01-21 18:12:53
- [x] Add GH admins to new team: roblabs
- [x] Add Location (San Diego) to chapters.json and /chapters page.

**Additional tasks**
- [x] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by roblabs** [comment]
Oops, please change it from _MaptimeSD_ to

**MaptimeSAN**

I prefer to use the Airport code for SAN.

**Comment by almccon** [comment]
Hi @roblabs! There was an earlier attempt (back in 2014) to create a Maptime in San Diego. I think they used MaptimeSD. For example: https://twitter.com/maptimesd

@jinlong25 was one of the organizers. I'm not sure if they ever had a meetup, though. 

Rob, if you send us an email at hello@maptime.io, I can put you in touch with some of the previous people who expressed interest in doing a San Diego Maptime. If they are still in town, they might be willing to help you.

**Comment by jinlong25** [comment]
Thanks @almccon !

Hi @roblabs, I was trying to host MaptimeSD a while back, but unfortunately I was relocated to Los Angeles for a new job. Let me know if you want to find people to co-host the chapter. I still have some connections at the Dept of Geography at SDSU. I'm also happy to hand over the MaptimeSD twitter account if you want to use it.

**Comment by roblabs** [comment]
@jinlong25 & @almccon, thanks!

We'll stick with MaptimeSD!!

**Comment by geobrando** [comment]
Hello @roblabs . I created a repo to manage your web page, which uses our starter template. I gave you write privileges.

repo: https://github.com/maptime/sandiego
site: http://maptime.io/sandiego

I edited your [_config.yml](https://github.com/maptime/sandiego/blob/gh-pages/_config.yml) to customize your site.  Let me know if you need help learning how to create posts/events on your site. You're also free to scrap this starter template if you prefer to build a custom web page.

I've also added you to the map and list at http://maptime.io/chapters by adding you to [chapters.json](https://github.com/maptime/maptime.github.io/blob/master/_data/chapters.json). If you feel comfortable doing so, please submit a pull request with any additional chapter information that I may have missed.

You should have received an invite to join our Slack, which is what we primarily use for communication between fellow organizers and with Maptime leadership (also known as MaptimeHQ). Please post any other questions you might have about how to get started building MaptimeSD in the #general channel on Slack. I'm `@brandon` there.  If you have been able to recruit any additional organizers, please send me a direct message with their name, email address, and github name.

I kept the MaptimeSD twitter handle in your config file and chapters.json.  Let me know if you don't take up @jinlong25's offer to hand it over and I'll remove from our records.

Thanks!

**Comment by roblabs** [comment]
Hello @jinlong25,

Yes, let's connect on the handle and credentials for twitter.com/MaptimeSD.

@geobrando — thanks for the fixing up the maptime.io/sandiego site.   We really like the #geoBreakfast & #geoBeers events that happen in SFO and DC.

**Comment by jinlong25** [comment]
Hi @roblabs,

I'm sending you the username and password in a sec on Slack ;-)
