### ISSUE TITLE
New Chapter for Edmonton, Alberta, Canada

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#170]
**Summary**
Maptime name: **MaptimeYEG**
Contact name: Devin Bartley
Date submitted: 2016-01-25 19:10:55
- [x] Add GH admins to new team: https://github.com/DevinLeeBartley
- [x] Add Location (Edmonton, Alberta, Canada) to chapters.json and /chapters page.

**Additional tasks**
- [x] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by almccon** [comment]
:maple_leaf: 🇨🇦

**Comment by almccon** [comment]
Added to Slack. Any other status updates?

**Comment by DevinLeeBartley** [comment]
Thanks Alan!

**Comment by geografa** [comment]
@DevinLeeBartley welcome to Maptime! I created a repo to manage your web page, which uses our starter template. I gave you write privileges. You're at this step right now:
https://github.com/maptime/edmonton#customizing-your-site

Your repo is here: https://github.com/maptime/edmonton
And your site is live: http://maptime.io/edmonton

Please customize your site by editing the _config.yml file in the gh-pages branch. I am happy to assist with this if help is needed. Let me know if you need help learning how to create posts/events on your site.

/cc @geobrando

**Comment by DevinLeeBartley** [comment]
Hello,

Thanks for getting this set up! I just tried to edit the _config.yml page
to update the chapter name and GitHub is telling me I don't have permission
to access it when I try to push my changes up.

Should I be forking a copy of the page and then submitting my changes via
pull requests, or is something wrong with my write permissions on the page?

Thanks

**Comment by geobrando** [comment]
@DevinLeeBartley Github shows that you were sent an invite to join the Maptime org and the edmonton admin team.  Can you check your email?  Junk mail, maybe?

**Comment by DevinLeeBartley** [comment]
Hello,

You are right, I had an email bured in my inbox. Everything is working
great now. I appreciate the help.

-Devin
