### ISSUE TITLE
New Chapter for Seoul, South Korea

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#171]
**Summary**
Maptime name: **MaptimeSeoul**
Contact name: Alana Kim
Date submitted: 2016-01-31 14:18:47
- [x] Add GH admins to new team: @alkims
- [x] Add Location (Seoul, South Korea) to chapters.json and /chapters page.

**Additional tasks**
- [x] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by almccon** [comment]
:kr: :rainbow:

**Comment by geobrando** [comment]
Hello @alkims. We created a repo to manage your web page, which uses our starter template. We gave you write privileges.

repo: https://github.com/maptime/seoul
site: http://maptime.io/seoul

We customized your site by editing the [_config.yml](https://github.com/maptime/seoul/blob/gh-pages/_config.yml) file in the gh-pages branch. We recommend securing a twitter handle and using it to promote your events and interact with your community. (e.g. `@MaptimeSeoul`). If you choose to create a twitter account, please update the _config.yml.  Let me know if you need help learning how to create posts/events on your site. You're also free to scrap this starter template if you prefer to build a custom web page.

We added MaptimeSeoul to the map and list at http://maptime.io/chapters by editing [chapters.json](https://github.com/maptime/maptime.github.io/blob/master/_data/chapters.json). If you feel comfortable doing so, please continue to edit this file with additional chapter information using the existing entries as an example and submit a pull request. If not, we can take care of that for you. Just respond to this issue.

You should have received an invite to join our Slack, which is what we primarily use for communication between fellow organizers and with Maptime leadership (also known as MaptimeHQ). Please post any other questions you might have about how to get started building MaptimeSeoul in the #general channel on Slack. I'm `@brandon` there.  If you have been able to recruit any additional organizers, please send me a direct message with their name, email address, and github name.

Thanks!
