### ISSUE TITLE
New Chapter for Istanbul

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#172]
**Summary**
Maptime name: **MaptimeIstanbul**
Contact name: fatih tas
Date submitted: 2016-02-02 19:10:37
- [x] Add GH admins to new team: 
- [x] Add Location (Istanbul) to chapters.json and /chapters page.

**Additional tasks**
- [x] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by almccon** [comment]
No github username or other contact information? Bummer, so I can't say 🇹🇷🌈, then. 😢

**Comment by geobrando** [comment]
@almccon There's an email address in the google sheet.  I'll send one and ask they sign up for a github account.

**Comment by fatihtas** [comment]
hey folks,
fatih here from Istanbul.
sorry for not providing github account before.. 
-fatih

**Comment by orkutmuratyilmaz** [comment]
hello all,

this Orkut from Istanbul and I'd be glad to join you:)

**Comment by geobrando** [comment]
Hello @fatihtas and @orkutmuratyilmaz . We created a repo to manage your web page, which uses our starter template. We gave you write privileges.

repo: https://github.com/maptime/istanbul
site: http://maptime.io/istanbul

We customized your site by editing the [_config.yml](https://github.com/maptime/istanbul/blob/gh-pages/_config.yml) file in the gh-pages branch. We recommend securing a twitter handle and using it to promote your events and interact with your community. (e.g. `@MaptimeIstanbul`). If you choose to create a twitter account, please update the _config.yml.  Let me know if you need help learning how to create posts/events on your site. You're also free to scrap this starter template if you prefer to build a custom web page.

We added MaptimeIstanbul to the map and list at http://maptime.io/chapters by editing [chapters.json](https://github.com/maptime/maptime.github.io/blob/master/_data/chapters.json). If you feel comfortable doing so, please continue to edit this file with additional chapter information using the existing entries as an example and submit a pull request. If not, we can take care of that for you. Just respond to this issue.

@fatihtas ... you should have received an invite to join our Slack, which is what we primarily use for communication between fellow organizers and with Maptime leadership (also known as MaptimeHQ). Please post any other questions you might have about how to get started building MaptimeIstanbul in the #general channel on Slack. I'm `@brandon` there.  If you have been able to recruit any additional organizers, please send me a direct message with their name, email address, and github name.

@orkutmuratyilmaz...  If you provide us with an email address, we can also add you to slack.

Thanks!
