### ISSUE TITLE
New Chapter for Trento, Italy

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#173]
**Summary**
Maptime name: **MaptimeTN**
Contact name: Trento, Italy
Date submitted: 2016-02-08 15:13:05
- [x] Add GH admins to new team: napo
- [x] Add Location (city) to chapters.json and /chapters page.

**Additional tasks**
- [x] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by almccon** [comment]
Exciting! But I'd suggest a less abbreviated name, like MaptimeTrento
:it: :rainbow:

**Comment by napo** [comment]
@almccon you are right, I discussed with the people around me and someone suggested "TN" because we can play with Trento (the city) or Trentino (the province).
TN is the abbreviation for "Province of TreNto" or for "TreNto"

**Comment by napo** [comment]
@geografa mmm
The right informations are:
Maptime name: MaptimeTN
Contact name: Maurizio Napolitano @napo 

The chapter is for Trento

**Comment by geobrando** [comment]
Hello @napo . We created a repo to manage your web page, which uses our starter template. We gave you write privileges.

repo: https://github.com/maptime/trento
site: http://maptime.io/trento

We customized your site by editing the [_config.yml](https://github.com/maptime/trento/blob/gh-pages/_config.yml) file in the gh-pages branch. We recommend securing a twitter handle and using it to promote your events and interact with your community. (e.g. `@MaptimeTrento`). If you choose to create a twitter account, please update the _config.yml.  Let me know if you need help learning how to create posts/events on your site. You're also free to scrap this starter template if you prefer to build a custom web page.

We added MaptimeTrento to the map and list at http://maptime.io/chapters by editing [chapters.json](https://github.com/maptime/maptime.github.io/blob/master/_data/chapters.json). If you feel comfortable doing so, please continue to edit this file with additional chapter information using the existing entries as an example and submit a pull request. If not, we can take care of that for you. Just respond to this issue.

You should have received an invite to join our Slack, which is what we primarily use for communication between fellow organizers and with Maptime leadership (also known as MaptimeHQ). Please post any other questions you might have about how to get started building MaptimeTrento in the #general channel on Slack. I'm `@brandon` there.  If you have been able to recruit any additional organizers, please send me a direct message with their name, email address, and github name.

Thanks!
