### ISSUE TITLE
New Chapter for Paris, France

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#174]
**Summary**
Maptime name: **MaptimeParis**
Contact name: Erik Escoffier
Date submitted: 2016-02-11 18:14:29
- [x] Add GH admins to new team: nerik
- [ ] Add Location (Paris, France) to chapters.json and /chapters page.

**Additional tasks**
- [x] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by nerik** [comment]
:fr: 🍾

**Comment by geografa** [comment]
Hello @nerik . I created a repo to manage your web page, which uses our starter template. I gave you write privileges.

repo: https://github.com/maptime/paris
site: http://maptime.io/paris

Please customize your site by editing the _config.yml file in the gh-pages branch. I am happy to assist with this if help is needed. Let me know if you need help learning how to create posts/events on your site.

I also added the website url to chapters.json which means it will render at http://maptime.io/chapters
