### ISSUE TITLE
milehigh post for march not appearing

### ISSUE THREAD

**Issue by mtaylorlong** [maptime/maptime-admin#176]
Hey Maptime team! I just pushed a post to the milehigh repo. I'm a little stumped why it isn't appearing on our site. I'm guessing it's something really simple I'm not seeing or understanding. Do you mind taking a look? https://github.com/maptime/milehigh/blob/gh-pages/_posts/2016-03-10-march-maptime-intro-to-osm.md

**Comment by geobrando** [comment]
Hmm..  Didn't see anything obvious so I took a stab at changing the title.  Did not work.

**Comment by emilyashley** [comment]
Is it because it's a future event? I think it no longer publishes future events by default, so we added “future:true” to our _config.yml file for upcoming events to appear.

**Comment by geobrando** [comment]
@emilyashley Good call!  Looks like something new with Jekyll 3.0, which github now uses.

**Comment by mtaylorlong** [comment]
Thanks @emilyashley and @geobrando!
