### ISSUE TITLE
New Chapter for Singapore

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#177]
**Summary**
Maptime name: **MaptimeSG**
Contact name: Christian Behrens, Vinutha Raghavendra
Date submitted: 2016-02-26 06:19:02
- [x] Add GH admins to new team: niceone, vinutha-singtel
- [x] Add Location (Singapore) to chapters.json and /chapters page.

**Additional tasks**
- [x] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by niceone** [comment]
Hi, I'm one of the admins of Maptime Singapore, and I have a question regarding the setup process: I saw that a Twitter account "maptimeSG" had been created that wasn't there a few days ago – so I assume this was done by you guys already? Any additonal info you nee from our side? Thanks!

**Comment by almccon** [comment]
Hi @niceone. Usually we don't set up twitter accounts for the new chapters... we leave it for the new organizers to do that. Maybe @vinutha-singtel did it?

**Comment by niceone** [comment]
No, she didn't set this one up either. Very strange. But thanks for the quick reply!

**Comment by niceone** [comment]
Okay, sorted it out. We're ready to go. :)

**Comment by vinutha-singtel** [comment]
Great!

Vinutha Raghavendra
DataSpark Pte Ltd
31B Exeter Road, Comcentre 2 Level 2, Singapore 239732

**Comment by vinutha-singtel** [comment]
Great!

**Comment by jenningsanderson** [comment]
:wave: Hi @niceone @vinutha-singtel, I'm trying to close out old issues here, how is Maptime Singapore? I'd like to add the link to Twitter to the chapters page at maptime.io/chapters, but I don't see https://twitter.com/MaptimeSG/ as active, are you all still meeting?

**Comment by philam** [comment]
Added MaptimeSG to map https://github.com/maptime/maptime.github.io/commit/1565cb316268801d1b81ff383d3383137093b742 Ping @geografa

**Comment by philam** [comment]
All tasks completed
