### ISSUE TITLE
New Chapter for Glasgow

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#178]
**Summary**
Maptime name: **MaptimeGlasgow**
Contact name: Andrew Lightfoot
Date submitted: 2016-03-07 15:59:48
- [x] Add GH admins to new team: eelsclash
- [ ] Add Location (Glasgow) to chapters.json and /chapters page.

**Additional tasks**
- [x] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by eelsclash** [comment]
I created a chapter approx. 3 weeks ago but I'm not sure if I did it right. This is a repeat request for a Glasgow chapter. How do I know when things are progressing? This request can be deleted if it is unnecessary.

**Comment by geografa** [comment]
HI @eelsclash ! No, you did everything correct. Thanks for the reminder! I've just been slow to get around to this. I created a repo to manage your web page, which uses our starter template. I gave you write privileges.

repo: https://github.com/maptime/glasgow
site will be: http://maptime.io/glasgow

Please customize your site by editing the [_config.yml](https://github.com/maptime/glasgow/blob/gh-pages/_config.yml) file in the gh-pages branch. I am happy to assist with this if help is needed. We recommend securing a twitter handle and using it to promote your events and interact with your community. (e.g. `@MaptimeGlasgow`). If you choose to create a twitter account, please update the _config.yml.  Let me know if you need help learning how to create posts/events on your site. You're also free to scrap this starter template if you prefer to build a custom web page.

We'll also need to get you added to the map and list at http://maptime.io/chapters. To do that, we will add your chapter to [chapters.json](https://github.com/maptime/maptime.github.io/blob/master/_data/chapters.json). If you feel comfortable doing so, please edit the file with your chapter information using the existing entries as an example and submit a pull request. If not, we can take care of that for you. Just respond to this issue.

You should have received an invite to join our Slack, which is what we primarily use for communication between fellow organizers and with Maptime leadership (also known as MaptimeHQ). Please post any other questions you might have about how to get started building MaptimeGlasgow in the #general channel on Slack. I'm `@geografa` there.  If you have been able to recruit any additional organizers, please send me a direct message with their name, email address, and github name.

Thanks!

**Comment by philam** [comment]
Did not add to map, no evidence of activity since 2016: https://github.com/maptime/glasgow
