### ISSUE TITLE
New Chapter for Albuquerque, NM, USA

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#179]
**Summary**
Maptime name: **MaptimeABQ**
Contact name: Brad Weikel
Date submitted: 2016-03-10 00:41:39
- [x] Add GH admins to new team: bradweikel, smallmelo
- [x] Add Location (Albuquerque, NM, USA) to chapters.json and /chapters page.

**Additional tasks**
- [x] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by bradweikel** [comment]
Just a friendly nudge. :) 

We've scheduled our first meetup and are itching to get things set up. Holler if you need anything from us.

**Comment by geografa** [comment]
hey @bradweikel ! thanks for your patience. Invite to repo sent. Notes forthcoming.

**Comment by geografa** [comment]
@bradweikel I created a repo to manage your web page, which uses our starter template. I gave you write privileges.

repo: https://github.com/maptime/albuquerque
site: http://maptime.io/albuquerque

Please customize your site by editing the _config.yml file in the gh-pages branch. I am happy to assist with this if help is needed. Let me know if you need help learning how to create posts/events on your site.

You will also need to add the website url to chapters.json which means it will render at http://maptime.io/chapters

Please let me know if that works out for you and if you have questions.

**Comment by bradweikel** [comment]
Thanks @geografa -- I'm fairly Jekyll-savvy so this looks like a breeze.

Could you add @smallmelo as well, to both the repo and Slack?

**Comment by geografa** [comment]
@bradweikel sweet. added @smallmelo but will need an email (DM me in slack) and I will add.
