### ISSUE TITLE
New Chapter for Brussels, Belgium

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#181]
**Summary**
Maptime name: **MaptimeBrussels**
Contact name: Tobrun Van Nuland
Date submitted: 2016-03-21 20:37:13
- [x] Add GH admins to new team: tobrun
- [ ] Add Location (Brussels, Belgium) to chapters.json and /chapters page.

**Additional tasks**
- [x] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by jbelien** [comment]
Hi @geografa ,

I just saw there is a new repo request for "MaptimeBRU" by @joostschouppe  (#207)  and a new repo request for "MaptimeBE" by myself (#212).

Could you add @joostschouppe, @marcu, @xivk, @Jorieke and myself @jbelien to MaptimeBrussels ?

Thanks !

**Comment by geobrando** [comment]
Hey @jbelien. Could you clarify something? Are you looking to start a chapter or join an existing organizing team?  I previously added @tobrun to our github org but his invitation is still pending.  Is there a current active chapter in Brussels?

**Comment by joostschouppe** [comment]
@geobrando :  @marcu, @xivk, @Jorieke, @jbelien and myself @joostschouppe are wanting to start a maptime chapter for Brussels (actually aiming for the whole of Belgium). We would be happy for @tobrun to join too.

There is no-one doing maptime anywhere in Belgium right now.

**Comment by jbelien** [comment]
@geobrando : 

Yeaaah... sorry for the mess.

The plan was to create an new chapter ( run by @Jorieke, @marcu, @xivk, @joostschouppe and myself @jbelien ).
@joostschouppe created an request (#207) for MaptimeBRU. Then I realised there is already a MaptimeBrussels.

Considering the size of our little country, I think that's not necessary to have maptime based on belgian cities (for the moment), so I would suggest to create **MaptimeBE** (#212) or rename **MaptimeBrussels** in **MaptimeBE** (if it's possible).

@tobrun is of course welcome to join this new **MaptimeBE** chapter :)

Like @joostschouppe said, there is **no** currently active maptime chapter in Belgium (or Brussels).

Thanks for your help

**Comment by tobrun** [comment]
Sorry for the confusion on this, feel free to grab MaptimeBrussels, recently moved away and have been too busy to actually make something happen there. Looking forward to join the first session and see what you guys are up to.

**Comment by geobrando** [comment]
Hi @jbelien I understand what you are saying, but after looking at the size of Belgium I am thinking that we might want to bring you in as an Brussels chapter.  We try to stay away from groups organizing chapters for entire nations.  While there may not be any current interest in other parts of the country,  your chapter should cover an area that is reasonable for your community to travel to get to your events.  What do you think?

**Comment by joostschouppe** [comment]
Hi Brandon,
I'm not sure. The list of accounts @jbelien provided includes people from
in or around Brussels, from Mons and from Antwerp. Most of our activities
are in Brussels and Antwerp, but people from Antwerp organize stuff in
Brussels and the other way around. If you prefer city-based maptime
chapters, I'd suggest creating two straight away: one for Brussels and one
for Antwerp. And include @jbelien's list in both chapters.
We do however have occasional activities in Mechelen, Gent, Leuven, Liege,
Namur and Louvain la Neuve too.

**Comment by jbelien** [comment]
@geobrando : 
Yes, I understand totally what you mean but, for the moment anyway, like @joostschouppe  said, we organize mapathons all around Belgium.

I think, if we can't create a Maptime Belgium Chapter, the best is to create a Maptime Brussels (MaptimeBRU) chapter for the moment and a Maptine Antwerp (MaptimeANT) chapter with the same administrators if possible and we hope there will be a lot of new chapters all around Belgium in the future ^^

Thanks a lot.

**Comment by geobrando** [comment]
Closed in favor of #212
