### ISSUE TITLE
New Chapter for Nîmes

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#183]
**Summary**
Maptime name: **MaptimeNîmes**
Contact name: Simonet
Date submitted: 2016-04-24 11:10:20
- [ ] Add GH admins to new team: Labo2
- [ ] Add Location (Nîmes) to chapters.json and /chapters page.

**Additional tasks**
- [ ] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by geobrando** [comment]
Hello @Labo2.  We created a repo you back in January.  See #157 

Is there anything else that we can do for you?
