### ISSUE TITLE
New Chapter for Capital Federal, Argentina

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#184]
**Summary**
Maptime name: **MaptimeBuenosAires**
Contact name: Agus
Date submitted: 2016-05-03 20:58:01
- [ ] Add GH admins to new team: no
- [ ] Add Location (Capital Federal, Argentina) to chapters.json and /chapters page.

**Additional tasks**
- [x] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by geobrando** [comment]
Email sent to organizer requesting a github account.  Waiting for response.

**Comment by philam** [comment]
No response, issue closed.
