### ISSUE TITLE
New Chapter for Yosemite, California, USA

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#185]
**Summary**
Maptime name: **MaptimeYOSE**
Contact name: Jim Soldenwagner
Date submitted: 2016-05-17 20:39:30
- [x] Add GH admins to new team: @jsoldenwagner
- [ ] Add Location (Yosemite, California, USA) to chapters.json and /chapters page.

**Additional tasks**
- [x] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by jsoldenwagner** [comment]
@geografa Is there anything else that needs to be done or can I start attempting to use maptime's jekyll template to start setting up maptimeYOSE's site?

**Comment by geografa** [comment]
Hey @jsoldenwagner ! Apologies, been really late getting to these issues. I created a repo to manage your web page, which uses our starter template. I gave you write privileges.

repo: https://github.com/maptime/yosemite
site: http://maptime.io/yosemite

Please customize your site by editing the _config.yml file in the gh-pages branch. I am happy to assist with this if help is needed. Let me know if you need help learning how to create posts/events on your site.

You will also need to add the website url to `chapters.json` which means it will render at http://maptime.io/chapters

Please let me know if you have questions!

**Comment by philam** [comment]
No evidence of activity since 2016 - did not add to map
