### ISSUE TITLE
New Chapter for Ottawa, Ontario, Canada

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#186]
**Summary**
Maptime name: **MaptimeOttawa**
Contact name: Nick Zachary
Date submitted: 2016-06-10 14:38:02
- [ ] Add GH admins to new team: 
- [ ] Add Location (Ottawa, Ontario, Canada) to chapters.json and /chapters page.

**Additional tasks**
- [x] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by geobrando** [comment]
Email sent requesting github account.  Waiting for response.

**Comment by philam** [comment]
No response, issue closed.
