### ISSUE TITLE
New Chapter for São Paulo, SP, Brazil

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#187]
**Summary**
Maptime name: **MaptimeSP**
Contact name: Bernardo Loureiro
Date submitted: 2016-06-18 14:12:47
- [x] Add GH admins to new team: https://github.com/bplmp
- [ ] Add Location (São Paulo, SP, Brazil) to chapters.json and /chapters page.

**Additional tasks**
- [x] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by almccon** [comment]
I added @bplmp to @maptime/br-saopaulo, and also to Slack. Someone else will have to help me do the other tasks.

**Comment by bplmp** [comment]
Ok, so it took me forever but now I'm really setting this chapter up. I don't have write access to the [São Paulo repo](https://github.com/maptime/saopaulo) though, can someone grant that to me?

**Comment by almccon** [comment]
Oops, try now!

**Comment by bplmp** [comment]
Works! Thanks!

**Comment by geografa** [comment]
👍
