### ISSUE TITLE
New Chapter for Spain

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#188]
**Summary**
Maptime name: **Maptime_prueba**
Contact name: prueba
Date submitted: 2016-06-27 11:26:14
- [ ] Add GH admins to new team: 
- [ ] Add Location (Spain) to chapters.json and /chapters page.

**Additional tasks**
- [ ] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by almccon** [comment]
This is a test, this is only a test.
