### ISSUE TITLE
New Chapter for GeoFort, Netherlands

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#189]
**Summary**
Maptime name: **Maptime Summercamp GeoFort**
Contact name: Erik Meerburg
Date submitted: 2016-07-05 20:37:27
- [x] Add GH admins to new team: @Geogoeroe 
- [ ] Add Location (GeoFort, Netherlands) to chapters.json and /chapters page.

**Additional tasks**
- [x] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by bricker0** [comment]
I LOVE the GeoFort! How are you collaborating with them? May I be involved?

**Comment by Geogoeroe** [comment]
Hey Britta,
You're welcome! The Maptime Summercamp takes place at GeoFort, 15-19 august. In daily life, I organize GIS/Cartography/etc courses, and GeoFort is the place where these courses take place. So it isn't too hard to organize a Maptime session there :-).
Sorry that my reaction is a bit delayed, don't have the hang of github yet. Twitter might be faster... @geogoeroe
Erik.

**Comment by philam** [comment]
No evidence of activity since 2017 (https://github.com/MaptimeSummercamp) - did not add to map
