### ISSUE TITLE
New Chapter for Lebanon (Upper Valley), NH, USA

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#190]
**Summary**
Maptime name: **MaptimeUV**
Contact name: Garrett Dash Nelson
Date submitted: 2016-07-06 15:26:13
- [x] Add GH admins to new team: user: garrettdashnelson
- [ ] Add Location (Lebanon (Upper Valley), NH, USA) to chapters.json and /chapters page.

**Additional tasks**
- [x] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by philam** [comment]
No evidence of activity after 2016 (https://twitter.com/maptimeuv) - did not add to map
