### ISSUE TITLE
New Chapter for Vero Beach, FL

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#192]
**Summary**
Maptime name: **MaptimeVero**
Contact name: Steve McKnight
Date submitted: 2016-07-15 23:51:36
- [ ] Add GH admins to new team: 
- [ ] Add Location (Vero Beach, FL) to chapters.json and /chapters page.

**Additional tasks**
- [ ] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by geobrando** [comment]
Email sent asking to contact asking for a github account

**Comment by geobrando** [comment]
Don't believe we ever received a response so closing.
