### ISSUE TITLE
New Chapter for Tacoma, Washington, USA.

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#193]
**Summary**
Maptime name: **MaptimeTacoma**
Contact name: Britta Ricker
Date submitted: 2016-07-24 18:06:19
- [x] Add GH admins to new team: bricker0
- [ ] Add Location (Tacoma, Washington, USA.) to chapters.json and /chapters page.

**Additional tasks**
- [x] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by philam** [comment]
No evidence of activity after 2016 - did not add to map

**Comment by geobrando** [comment]
Reached out at https://github.com/maptime/tacoma/issues/1 to ask for a status update. Will fulfill if still needed
