### ISSUE TITLE
New Chapter for Grand Junction, Colorado, USA

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#194]
**Summary**
Maptime name: **MaptimeWestSlope**
Contact name: Nolan
Date submitted: 2016-07-26 17:37:21
- [x] Add GH admins to new team: vespax
- [ ] Add Location (Grand Junction, Colorado, USA) to chapters.json and /chapters page.

**Additional tasks**
- [x] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by geobrando** [comment]
Hello @vespax. I created a repo to manage your web page, which uses our starter template. I gave you write privileges.

repo: https://github.com/maptime/westslope
site: http://maptime.io/westslope

I customized your site by editing the [_config.yml](https://github.com/maptime/westslope/blob/gh-pages/_config.yml) file in the gh-pages branch. We recommend securing a twitter handle and using it to promote your events and interact with your community. (e.g. `@MaptimeWestSlope`). If you choose to create a twitter account, please update the _config.yml.  We can assist if you need help doing so. Let me know if you need help learning how to create posts/events on your site. You're also free to scrap this starter template if you prefer to build a custom web page.

We'll also need to get you added to the map and list at http://maptime.io/chapters. To do that, we will add your chapter to [chapters.json](https://github.com/maptime/maptime.github.io/blob/master/_data/chapters.json). If you feel comfortable doing so, please edit the file with your chapter information using the existing entries as an example and submit a pull request. If not, we can take care of that for you. Just respond to this issue.

You should have received an invite to join our Slack, which is what we primarily use for communication between fellow organizers and with Maptime leadership (also known as MaptimeHQ). Please post any other questions you might have about how to get started building MaptimWestSlope in the #general channel on Slack. I'm `@brandon` there.  If you have been able to recruit any additional organizers, please send me a direct message with their name, email address, and github name.

Thanks!

**Comment by Ranger444** [comment]
Hey Brandon,

If you wouldn't mind adding us to chapters.json that would be awesome. I don't know how to properly write code.

Location: Grand Junction, Colorado
Title: WesternSlopeMaptime
Website: http://maptime.io/westslope
Meetup: https://www.meetup.com/Western-Slope-OpenStreetMap/
Github:  https://github.com/maptime/westslope
Organizers: Nolan, Aaron

That would be awesome thank you.

**Comment by philam** [comment]
No evidence of activity since 2017 (https://twitter.com/MaptimeWestCO/) - did not add to map

**Comment by geobrando** [comment]
Hey @Ranger444. Closing this but let us know if you're still active and if anything else is still needed.
