### ISSUE TITLE
New Chapter for GeoFort, Netherlands

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#195]
**Summary**
Maptime name: **MaptimeSummercamp**
Contact name: Erik Meerburg
Date submitted: 2016-07-28 16:05:32
- [ ] Add GH admins to new team: 
- [ ] Add Location (GeoFort, Netherlands) to chapters.json and /chapters page.

**Additional tasks**
- [ ] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by almccon** [comment]
Duplicate of #189
