### ISSUE TITLE
New Chapter for Canada

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#196]
**Summary**
Maptime name: **MaptimeNM**
Contact name: mehtaneelu2000@yaho.ca, usersname Nmehta
Date submitted: 2016-07-30 04:19:05
- [ ] Add GH admins to new team: no
- [ ] Add Location (Canada) to chapters.json and /chapters page.

**Additional tasks**
- [ ] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by almccon** [comment]
Did they pick NM because that's their initials? Neelu Mehta?

Closing because no reliable information was given. If you wish to reopen, please specify an actual city or region in Canada.
