### ISSUE TITLE
New Chapter for Tampa Bay Area, Florida, USA

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#197]
**Summary**
Maptime name: **MaptimeTampaBay**
Contact name: Alexandra Fredericks
Date submitted: 2016-08-13 13:12:04
- [x] Add GH admins to new team: 
- [ ] Add Location (Tampa Bay Area, Florida, USA) to chapters.json and /chapters page.

**Additional tasks**
- [x] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by XanFredericks** [comment]
I look forward to getting St Pete and the greater Tampa Bay Area involved!!

**Comment by philam** [comment]
No evidence of activity since 2016 - did not add to map https://github.com/maptime/tampabay

**Comment by geobrando** [comment]
Hi @XanFredericks Looks like you have not yet added and content to the site we created. Can you tell us if you are or are planning to hold any meetings? If not we'll go ahead and close this and can disable the site. If you were added to Slack and want to discuss there you can do so in the admin channel

**Comment by XanFredericks** [comment]
Thanks for reaching out. I’m no longer in the state so please proceed with closing and disabling. 

Thank you, again.
