### ISSUE TITLE
New Chapter for Alicante, Spain

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#198]
**Summary**
Maptime name: **MaptimeALC**
Contact name: Nur
Date submitted: 2016-09-02 22:15:57
- [ ] Add GH admins to new team: 
- [ ] Add Location (Alicante, Spain) to chapters.json and /chapters page.

**Additional tasks**
- [x] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by geobrando** [comment]
Added to Slack and sent email requesting a github handle.

**Comment by geobrando** [comment]
Do not we ever received a response so closing
