### ISSUE TITLE
Ideas for future sessions

### ISSUE THREAD

**Issue by jacquestardie** [maptime/maptime-admin#20]
- [ ] QGIS
- [ ] Tilemill
- [ ] Tilemill2
- [ ] CartoCSS
- [ ] GeoJSON
- [ ] Field Papers
- [ ] CartoDB
- [ ] OSM 201
- [ ] [Extract, Transform, Load (ETL) Workflows](https://github.com/maptime/maptime/issues/21)
- [ ] Cartography principles 
- [ ] What makes good data? 
- [ ] Surveying w/ gps 
- [ ] Surveying w/o gps

**Comment by zhiqiangZHAO** [comment]
QGIS!!!

**Comment by jacquestardie** [comment]
Are folks ok with closing this? We seem to have moved beyond the point where coming up with new topics is an issue, and more into the realm of curating all the fantastic presentations that have already occured.

**Comment by geografa** [comment]
:+1:
