### ISSUE TITLE
New Chapter for Cardiff, UK

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#200]
**Summary**
Maptime name: **MaptimeCardiff**
Contact name: Rose-Ellen Minchew
Date submitted: 2016-09-08 14:25:39
- [x] Add GH admins to new team: rocketnelly
- [x] Add Location (Cardiff, UK) to chapters.json and /chapters page.

**Additional tasks**
- [x] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by rocketnelly** [comment]
can someone advise me on the next stages?

**Comment by geobrando** [comment]
Hello @rocketnelly . I created a repo to manage your web page, which uses our starter template. I gave you write privileges.

repo: https://github.com/maptime/cardiff
site: http://maptime.io/cardiff

I customized your site by editing the [_config.yml](https://github.com/maptime/cardiff/blob/gh-pages/_config.yml) file in the gh-pages branch.  We recommend securing a twitter handle and using it to promote your events and interact with your community. (e.g. `@MaptimeCardiff`). If you choose to create a twitter account, please update the _config.yml.  I am happy to assist with this if help is needed. Also, let me know if you need help learning how to create posts/events on your site. You're also free to scrap this starter template if you prefer to build a custom web page.

We'll also need to get you added to the map and list at http://maptime.io/chapters. To do that, we will add your chapter to [chapters.json](https://github.com/maptime/maptime.github.io/blob/master/_data/chapters.json). If you feel comfortable doing so, please edit the file with your chapter information using the existing entries as an example and submit a pull request. If not, we can take care of that for you. Just respond to this issue.

You should have received an invite to join our Slack, which is what we primarily use for communication between fellow organizers and with Maptime leadership (also known as MaptimeHQ). Please post any other questions you might have about how to get started building MaptimeCardiff in the #general channel on Slack. I'm `@brandon` there.  If you have been able to recruit any additional organizers, please send me a direct message with their name, email address, and github name.

Thanks!

**Comment by rocketnelly** [comment]
Hello!

Thank you for setting this up for me!  I think I have added myself onto the
map but it hasn't showed up yet so I may have made a mistake?   How do I go
about making the website for MaptimeCardiff?

Thanks!
