### ISSUE TITLE
New Chapter for Canberra Australia

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#201]
**Summary**
Maptime name: **MaptimeCBR**
Contact name: Louise Maher
Date submitted: 2016-09-13 22:20:03
- [ ] Add GH admins to new team: 
- [ ] Add Location (Canberra Australia) to chapters.json and /chapters page.

**Additional tasks**
- [x] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by geobrando** [comment]
Sent email to organizer requesting a github account.
