### ISSUE TITLE
New Chapter for San Juan, Metro Manila, Philippines

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#202]
**Summary**
Maptime name: **MapAmoreTime**
Contact name: Erwin Olario
Date submitted: 2016-09-14 00:54:33
- [ ] Add GH admins to new team: https://github.com/govvin
- [ ] Add Location (San Juan, Metro Manila, Philippines) to chapters.json and /chapters page.

**Additional tasks**
- [x] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by govvin** [comment]
hi @geografa 

Sorry for being a bit thick here. What's the next step I'm supposed to do here?

**Comment by geobrando** [comment]
hey @govvin Apologies for the delay.  Maptime is going through a transition at the
moment and as result we are not able to respond as quickly as we would like
to chapter requests.  Thank you for your patience while we figure this
out.  Be assured that we have not forgotten about you.

Thanks

**Comment by geobrando** [comment]
Apologies for the delay.  Maptime is going through a transition at the
moment and as result we are not able to respond as quickly as we would like
to chapter requests.  Thank you for your patience while we figure this
out.  Be assured that we have not forgotten about you.

Thanks

**Comment by govvin** [comment]
Thanks @geobrando . I got added in Slack a few days ago, looking forward to hearing back from you and working on out chapter webpage.

**Comment by geobrando** [comment]
@govvin So can we change your name to something like MaptimeManila?  We recommend chapter names that will help to easily identify your city or region.

**Comment by govvin** [comment]
Not a problem, @geobrando. In that case, MaptimeManila sounds good.

**Comment by govvin** [comment]
I have a pull request for a new entry to chapter.json: 

https://github.com/maptime/maptime.github.io/pull/285

**Comment by philam** [comment]
Already added to map
