### ISSUE TITLE
New Chapter for Arcata, CA, USA

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#203]
**Summary**
Maptime name: **MaptimeHumboldt**
Contact name: Nicholas Perdue
Date submitted: 2016-09-19 22:23:50
- [ ] Add GH admins to new team: dikembe3000
- [ ] Add Location (Arcata, CA, USA) to chapters.json and /chapters page.

**Additional tasks**
- [x] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by geobrando** [comment]
Hey @dikembe3000.  Thanks for the interest.  Are you interested in a chapter based at Humboldt State University?

**Comment by dikembe3000** [comment]
Not at HSU, but for the entire community. I've having trouble getting it loaded up

**Comment by geobrando** [comment]
@dikembe3000 Looks like you were partially onboarded as you are on the chapter list but I don't see a chapter repo for your site. This was over 5 years ago so let us know if you either are no longer running interested in running a chapter or still need to be onboarded. Closing this for now but can reopen.
