### ISSUE TITLE
New Chapter for Tempe, Arizona, USA

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#205]
**Summary**
Maptime name: **MaptimeAZ**
Contact name: Kimberly Shaffer
Date submitted: 2016-09-29 06:25:52
- [ ] Add GH admins to new team: N/A
- [ ] Add Location (Tempe, Arizona, USA) to chapters.json and /chapters page.

**Additional tasks**
- [x] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by geobrando** [comment]
Sent email to organizer requesting a github account

**Comment by almccon** [comment]
Also, "Tempe" is too specific, but "MaptimeAZ" is probably too broad. MaptimePHX perhaps?

**Comment by geobrando** [comment]
Don't believe we ever got a response via email and can't locate her in Slack so closing
