### ISSUE TITLE
New Chapter for Brussels, Belgium

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#207]
**Summary**
Maptime name: **MaptimeBRU**
Contact name: Joost Schouppe
Date submitted: 2016-10-12 10:27:39
- [ ] Add GH admins to new team: joostschouppe, marcu, xivk, Jorieke
- [ ] Add Location (Brussels, Belgium) to chapters.json and /chapters page.

**Additional tasks**
- [ ] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by geobrando** [comment]
Closed in favor of #212
