### ISSUE TITLE
New Chapter for Affenland

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#209]
**Summary**
Maptime name: **AffeMap**
Contact name: affe
Date submitted: 2016-10-14 12:48:21
- [ ] Add GH admins to new team: Affen
- [ ] Add Location (Affenland) to chapters.json and /chapters page.

**Additional tasks**
- [ ] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by geobrando** [comment]
Does not appear to be a legitimate request.
