### ISSUE TITLE
New Chapter for Bristol, UK

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#210]
**Summary**
Maptime name: **MaptimeBristol**
Contact name: Magnus Erichsen
Date submitted: 2016-10-18 07:49:09
- [ ] Add GH admins to new team: 
- [ ] Add Location (Bristol, UK) to chapters.json and /chapters page.

**Additional tasks**
- [x] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by magsderich** [comment]
Hi Brandon, sorry for delay. Standard starter template is fine for us, do you need any other details?

Thanks,
Magnus

**Comment by magsderich** [comment]
Hi @geografa , just came back to this and arranged our first event for May, would like to complete onboarding if possible. Thanks!

**Comment by philam** [comment]
No evidence of activity since 2017 - did not add to map https://twitter.com/MaptimeBristol

**Comment by geobrando** [comment]
@magsderich Closing this but can reopen and finish onboarding if you are still active
