### ISSUE TITLE
New Chapter for Belgium

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#212]
**Summary**
Maptime name: **MaptimeBE**
Contact name: Jonathan Beliën
Date submitted: 2016-10-25 08:11:43
- [x] Add GH admins to new team: jbelien & joostschouppe
- [x] Add Location (Belgium) to chapters.json and /chapters page.

**Additional tasks**
- [x] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by jbelien** [comment]
Hi @geografa ,

Could you add @marcu, @xivk and @Jorieke also as admins ?

Thanks !

**Comment by geobrando** [comment]
Closed in favor of #181

**Comment by jbelien** [comment]
Thanks a lot @geobrando !!
I'll have a look at it next week :)

**Comment by jbelien** [comment]
Just did a Pull Request to update `chapters.json` : https://github.com/maptime/maptime.github.io/pull/284

**Comment by jbelien** [comment]
My previous Pull Request wasn't successful checked by TravisCI so I fixed it !

**Comment by philam** [comment]
Already added to map
