### ISSUE TITLE
New Chapter for Cardiff, UK

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#213]
__Summary__
Maptime name: __MaptimeCardiff__
Contact name: Rose-Ellen Minchew
Date submitted: 2016-11-06 21:39:57

- [ ] Add GH admins to new team: rocketnelly
- [ ] Add Location (Cardiff, UK) to chapters.json and /chapters page.

__Additional tasks__
- [ ] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by geobrando** [comment]
Hi @rocketnelly.  Getting to your request right now.  Apologies for the delay
