### ISSUE TITLE
New Chapter for Melbourne, Victoria, Australia

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#215]
__Summary__
Maptime name: __MaptimeMelbourne__
Contact name: Philip Mallis
Date submitted: 2016-11-16 03:45:09

- [x] Add GH admins to new team: philam
- [x] Add Location (Melbourne, Victoria, Australia) to chapters.json and /chapters page.

__Additional tasks__
- [x] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by philam** [comment]
Occurred to me that 'Melbourne, Australia' is enough, no need to include 'Victoria' :)

**Comment by philam** [comment]
Hi :) Any update on this?

**Comment by geobrando** [comment]
Hi @philam Maptime is going through a big transition in leadership right now and as a result is not able to respond very quickly to requests.  Thanks for being patient.  Hopefully, someone will reach out to you shortly should you wish to host a website on maptime.io.  But I went ahead and added you to our Slack team, so feel free to reach out there with any questions about getting started.  Other organizers regularly monitor the general channel and questions for Maptime leadership can be made in the admin channel.  I'm 'brandon' there.

 There's no real approval needed so you absolutely start organizing events, recruiting additional organizers, etc. Would recommend creating a twitter account such as MaptimeMelbourne.   Also, most chapters use Meetup.com to advertise their events.

**Comment by stevage** [comment]
Hi @philam - fellow Melburnian. I'd love to help get a Maptime started, and know two other people interested as well. I'm out of town for the next two weeks but would love to catch up and discuss in early Feb. Maybe email me? stevage@gmail.com.

**Comment by eneerhut** [comment]
Would love to catch up and discuss also @philam. I was planning to meet @stevage in Feb to discuss and he just emailed me informing you're a step ahead. Fantastic to see.

**Comment by philam** [comment]
@stevage @eneerhut Sounds great! If you find me on the Maptime Slack (same username: philam) we can have a chat there as well, but I shoot off an email now.

**Comment by philam** [comment]
Slack channel: https://maptimeaustralia.slack.com

**Comment by philam** [comment]
Added to map! https://github.com/maptime/maptime.github.io/commit/189944593cca215452f92e2819125213e3c3f14d

**Comment by eneerhut** [comment]
Wooh! Nice @philam.
Funny seeing the conversation from early 2017.
