### ISSUE TITLE
New Chapter for Athens, Georgia, USA

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#218]
__Summary__
Maptime name: __MaptimeAthens__
Contact name: David
Date submitted: 2017-02-12 00:41:15

- [x] Add GH admins to new team: shann039, drickless, 
- [ ] Add Location (Athens, Georgia, USA) to chapters.json and /chapters page.

__Additional tasks__
- [ ] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by almccon** [comment]
Probably should be named something _slightly_ different, in case, you know, the original Athens wants to start a Maptime. :)

**Comment by drickless** [comment]
@almccon Good point. How about MaptimeATH or MaptimeAthensGA? It's a college town, so we considered MaptimeUGA, but we're trying to use the name of the city to be more inclusive.

**Comment by almccon** [comment]
MaptimeAthensGA sounds good to me. I agree that it's better to name the Maptime after the town, not the school.

**Comment by geobrando** [comment]
@drickless Did you eventually form this chapter?  Let me know if there is anything you need or if I can close this ticket.

**Comment by drickless** [comment]
@geobrando You can close the ticket. The chapter was created but I don’t know the current status as it’s been a few years since I was involved.
