### ISSUE TITLE
New Chapter for Tirana, Albania

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#220]
__Summary__
Maptime name: __MaptimeTirana__
Contact name: Amanti Lulo
Date submitted: 2017-03-21 14:46:44

- [x] Add GH admins to new team: diskmanti
- [x] Add Location (Tirana, Albania) to chapters.json and /chapters page.

__Additional tasks__
- [x] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by diskmanti** [comment]
Hello

I am diskmanti. I made this request to open a MapTime chapter in my hometown, Tirana. I was wondering when will my request be approved and if there was anything missing from the form I completed. Hope everyting is ok.

Keep up the great work.
Cheers,
Amanti

**Comment by almccon** [comment]
You now have a repo at http://github.com/maptime/tirana, and the website is as http://maptime.io/tirana. Let me know if you can't access it!

**Comment by diskmanti** [comment]
Hello

I can access everything. Thanks you for the great work. I will be adding my first event by Monday(hopefully).
Just on more question. How can I add someone else on my chapter. Another member to publish posts and so on?

Thanks again,
Amanti

**Comment by almccon** [comment]
Hi @diskmanti, if you want to have other co-organizers who can publish posts, just tell me their github usernames. I will add them to the repo.

**Comment by diskmanti** [comment]
Hello,

I am writing here as I do not know if there is a specific place to as questions about management. If there are other ways of communications please tell me.

I want to know if there are some guidelines on how to manage a local maptime chapter. I have searched the issues on this repo and have discovered this [link](http://maptime.io/blog/2015/01/13/learning-together-in-2015) 

Do I have to follow that guideline or I can discuss topics on my local chapter as I see fit? 

Thanks in advance.  😄

**Comment by almccon** [comment]
Hi @diskmanti! Our Slack group is the best place to ask these questions. If you're not on it yet, send an email to hello@maptime.io, and we'll send you an invitation to join.

**Comment by diskmanti** [comment]
@almccon Thanks 😃

**Comment by philam** [comment]
Already added to map
