### ISSUE TITLE
New Chapter for Sydney, NSW, Australia

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#221]
__Summary__
Maptime name: __MaptimeSyd__
Contact name: Elise McKenna
Date submitted: 2017-03-23 11:22:16

- [ ] Add GH admins to new team: mappingmckenna
- [ ] Add Location (Sydney, NSW, Australia) to chapters.json and /chapters page.

__Additional tasks__
- [ ] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by mappingmckenna** [comment]
Hi @geografa - just following up on this - any idea on when we can expect to have our chapter up?
Cheers!

**Comment by philam** [comment]
Hello from Maptime Melbourne! :)

**Comment by philam** [comment]
No evidence of activity since 2017 - did not add to map

**Comment by geobrando** [comment]
@mappingmckenna  Hi. Ignore the email I just sent. Didn't realize you already on this thread.  Let me know if there is anything I can do for you, otherwise I'll close this.

**Comment by geobrando** [comment]
Closed at request of @mappingmckenna via email
