### ISSUE TITLE
New Chapter for Adelaide

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#222]
__Summary__
Maptime name: __Digital Cartography__
Contact name: Stefan
Date submitted: 2017-05-26 14:26:05

- [ ] Add GH admins to new team: OK
- [ ] Add Location (Adelaide) to chapters.json and /chapters page.

__Additional tasks__
- [ ] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by almccon** [comment]
Not sure what "Digital Cartography" means in this context. Is it university department or something? I think the simple name *MaptimeAdelaide* would be best.

Also, looks like we need a github username and/or an email address for "Stefan" before this can become actionable.

**Comment by philam** [comment]
FYI the Slack channel for Australian Maptime chapters is located here if our Radelaide friends want in :) https://maptimeaustralia.slack.com

**Comment by philam** [comment]
No evidence of activity since 2017 - did not add to map
