### ISSUE TITLE
New Chapter for Snoqualmie, Washington, US

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#223]
__Summary__
Maptime name: __MaptimeEastside__
Contact name: Heather Minnella
Date submitted: 2017-06-03 01:36:53

- [ ] Add GH admins to new team: spaceof7
- [ ] Add Location (Snoqualmie, Washington, US) to chapters.json and /chapters page.

__Additional tasks__
- [ ] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by almccon** [comment]
MaptimeEastside should probably be something more like MaptimeSnoqualmie. Maptime chapter names should be relatively distinct, and there's a good chance that there are tons of other places in the world that call themselves "Eastside".

**Comment by philam** [comment]
No evidence of activity since 2017 - did not add to map

**Comment by geobrando** [comment]
Looks like a repo was cloned for them but that was the only task completed. Responded to the email Heather sent in to 2018 to see if this is still needed cc @spaceof7

**Comment by geobrando** [comment]
That was fast.  Per Heather's response I am closing this and deleting the repo
