### ISSUE TITLE
New Chapter for Turin

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#225]
__Summary__
Maptime name: __MaptimeTurin__
Contact name: Alessandro Calvi
Date submitted: 2017-06-16 14:28:38

- [ ] Add GH admins to new team: 
- [ ] Add Location (Turin) to chapters.json and /chapters page.

__Additional tasks__
- [ ] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by jenningsanderson** [comment]
@geografa - could this issue template also be populated with the email of the requester so we can try to get the missing information? (ie, in this case, the GH admins)

**Comment by jenningsanderson** [comment]
Also, closing this because they issued a new request with this missing info 💯
