### ISSUE TITLE
New Chapter for Turin 

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#226]
__Summary__
Maptime name: __MaptimeTurin__
Contact name: Alessandro Calvi
Date submitted: 2017-06-19 14:43:31

- [x] Add GH admins to new team: https://github.com/alecalvi
- [ ] Add Location (Turin ) to chapters.json and /chapters page.

__Additional tasks__
- [ ] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by alecalvi** [comment]
Can you add Turin tu Chapters page? Thanks

**Comment by geobrando** [comment]
Hey @alecalvi If you're still running a maptime chapter and need us to add you to the chapter list or anything else please let us know.  I'm going to close this for now but will reopen if you do. It's been nearly 5 years so I suspect you don't. Thanks.
