### ISSUE TITLE
New Chapter for San Diego, California, USA

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#227]
__Summary__
Maptime name: __MaptimeSD__
Contact name: Madison Draper
Date submitted: 2017-08-02 22:09:17

- [ ] Add GH admins to new team: madizhen
- [ ] Add Location (San Diego, California, USA) to chapters.json and /chapters page.

__Additional tasks__
- [ ] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by almccon** [comment]
Hi @madizhen. We already had a San Diego group that tried to start up a few years ago, so https://github.com/maptime/sandiego already exists. We should try to get in touch with the previous organizers and see if they can help you restart the group!

**Comment by mzdraper** [comment]
Thank you! Do I need to be an admin for that repo or can we just use it?

**Comment by almccon** [comment]
I just added you. Looks like @roblabs is the other member of @maptime/us-ca-sandiego, although I remember a few other people were involved before that, but I'd have to dig a while to find out who they are. I think they all moved away from San Diego, perhaps.

**Comment by almccon** [comment]
Also, @madizhen, send an email to hello@maptime.io and somebody will then send you an invite to our Slack channel. Once you get there, you'll find more people who will help show you the ropes. Good luck! 🌈

**Comment by almccon** [comment]
And you should find out if anyone is still running twitter.com/MaptimeSD, and see if they'll pass it along to you.

**Comment by mzdraper** [comment]
I'll do all of that now. Thanks so much for setting this up @almccon!

**Comment by roblabs** [comment]
Hello @madizhen — I have the credentials for twitter.com/MaptimeSD

I am still in San Diego and would love to see the Maptime reinvigorated.  Once you are on slack, we can connect there (@RobLabs)

**Comment by jenningsanderson** [comment]
Hi @madizhen :wave: I'm checking up on open issues... Is everything set for Maptime San Diego? Can I close this issue?

**Comment by philam** [comment]
Already added to map
