### ISSUE TITLE
New Chapter for THRISSUR,KERALA,INDIA

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#229]
__Summary__
Maptime name: __MaptimeTCR__
Contact name: AJITHKUMAR
Date submitted: 2017-08-10 16:59:16

- [ ] Add GH admins to new team: 
- [ ] Add Location (THRISSUR,KERALA,INDIA) to chapters.json and /chapters page.

__Additional tasks__
- [ ] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by philam** [comment]
No evidence of activity - did not add to map
