### ISSUE TITLE
Need some help with onboarding new chapters?

### ISSUE THREAD

**Issue by philam** [maptime/maptime-admin#234]
This is getting a tad silly. Some chapters have been waiting for over a year to be listed on the Maptime website and/or be fully 'on-boarded' through the process. See the Melbourne chapter #215 for my experience.

I fully appreciate that the organisers have many other things to do in their lives, and that's totally fine. But when basic admin like this is not completed it doesn't look good for the organisation nor does it inspire confidence for other people to start chapters. Not to mention the fact that many chapters are not listed on the Maptime website for people to find.

With that, if the reason behind this is a lack of time on the part of the organisers, I will stick my hand up to help out with onboarding new chapters. I'm sure that others would do the same.

**Comment by jenningsanderson** [comment]
Hi @philam, let's do something about this, sticking my hand up too ✋  The [maptime](http://maptime.io) homepage also needs updating.

The current onboarding process is done via the `onboarding.sh` script. I think one reason for the backlog is a lack of complete information (such as github usernames) and/or lack of consensus on chapter names at first; these issue tickets are automatically generated and then much of this is never resolved. @geografa walked me through this script last year and then I got overwhelmed with other obligations and didn't stay on top of it 👎. 

I'd like to propose a time in the coming weeks where anyone who's got some time could hop on a Google Hangout and we could do a little Maptime update sprint, we can call it _"Prepping Maptime for 2018"_  Ping me on slack and let's try to find a time? 

Such a Sprint could include: 

- [ ] Onboarding backlog: resolve the 81 open issues
- [ ] Update chapters.json and/or redesign to be something easier to work with (consider a Google Doc that's easier to update / manage than .json file?  (we can export to .json for the jekyll build) 
- [ ] Update maptime.io to display the above (consider updating map to GL, maybe with a fun "#Maptime" style? )
- [ ] Write a new post for the front page of Maptime.io

/cc @emilyashley @rsteve388

**Comment by rstevensonUSGS** [comment]
I did a bunch of the backlog in October when I had help. But to be honest. I am not sure what I am doing so I could use a basic understanding of the process. Now that the semester is over, I am game for helping with this, Jennings when were you thinking of doing this sprint?

**Comment by rstevensonUSGS** [comment]
@philam are you on the maptime slack? Can we have this conversation there?

**Comment by geografa** [comment]
@philam I totally get the frustration and you're right - things have fallen behind beyond a reasonable time. The issue here IMO is that this model doesn't scale. Others will take it over and it will continue to get dropped because it requires numerous steps to onboard and maintain the repos. I'd like to propose that the model **completely change to an autonomous one** where the Maptime org simply maintains the main website and individual chapters provide their own website. This means:
- shutting down the chapter registration
- auditing chapters for activity
- update list of active chapters
- create new self-service method for getting listed (e.g. pull from [twitter api](https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/user-object) for account to show chapter location)

cc @rstevensonUSGS @almccon

**Comment by jenningsanderson** [comment]
👍  @geografa, I like this; perhaps an opt-in option for the maptime/<chapter> repository. As it stands, many repos are not used. Perhaps change to a Google Form & Spreadsheet for managing Chapter listings? Happy to talk more on this...

**Comment by philam** [comment]
@jenningsanderson @geografa Sounds great! If decentralisation/autonomy means that chapters can be more quickly put on their feet and supported, then it sounds good to me. 

I think that a good first step would be consulting chapters on any changes. Perhaps a general survey about the support that they have had/would like to see from Maptime. Then that could guide any future development on this subject and see how the central organisation can best support existing, new and future chapters.

**Comment by geografa** [comment]
@philam can you post back here if you decide to make a work session to hammer out ideas? Happy to help if I can make it.

**Comment by jenningsanderson** [comment]
:wave: @geografa - hoping for Monday, January 8, 2018; 5pm Mountain Time; conversation is also taking place in #admin on slack!

**Comment by emilyashley** [comment]
Happy to comment that this meeting did indeed take place! Translating notes into follow up issues 👍
