### ISSUE TITLE
Maptime Chapters Census 2018

### ISSUE THREAD

**Issue by jenningsanderson** [maptime/maptime-admin#236]
Goal: Perform a census of the Maptime chapters in order to update the maptime.io/chapters page with current contact information. This would be a simple and short survey: 

1. Chapter name & location? 
2. Where can we find you? (Meetup? Facebook? Twitter?)

What other details should be in here?

**Comment by philam** [comment]
Do we need to know if they have/want a Maptime.io webpage? Or is it easier for us to check from the backend?

**Comment by jenningsanderson** [comment]
@philam - I think we should do that part by hand -- based on the responses we get, we'll be able to follow up with the chapter organizers and see if they need the github repo.  Likewise, we should offer maptime.io/ namespaces to chapters that already have other websites, but these could likely be done better as follow up conversations with chapter organizers.

**Comment by emilyashley** [comment]
Good news! Just got a request for a chapter restart for Baltimore, MD so soon, at least 1 of xxxx chapters will be up to date in our repo. 

https://github.com/maptime/maptime-admin/issues/244

**Comment by emilyashley** [comment]
assigning this so it stays in my https://github.com/issues/assigned view. tagged @jenningsanderson as well.

@philam would you also like to be assigned? Do you have access to all the repo's etc that you need?

**Comment by philam** [comment]
@emilyashley Sure I'm happy to be assigned. I'm pretty sure that I have all of the necessary permissions. I'll let you know if I find out later that I don't!

**Comment by philam** [comment]
Actually @emilyashley I've just checked and I don't have edit access to the maptime.github.io repo so I can't edit the file to add new chapters.

**Comment by emilyashley** [comment]
@philam I think I sent you and invite to the correct team now :) Thanks for helping.

Feel free to assign me on any pull requests for review as well.

**Comment by geobrando** [comment]
This is nearly 4 years old so needs to be repeated.  Going to close this and if anyone who sees this and is still interested in doing something similar let's discuss on Slack in the admin channel
