### ISSUE TITLE
New Chapter for Duluth, Minnesota, USA

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#237]
__Summary__
Maptime name: __MaptimeDuluth__
Contact name: Zachary Vavra
Date submitted: 2018-01-18 12:56:24

- [ ] Add GH admins to new team: Zachary Vavra
- [ ] Add Location (Duluth, Minnesota, USA) to chapters.json and /chapters page.

__Additional tasks__
- [ ] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by geobrando** [comment]
Reached out to Zachary over email to see if this is still needed

**Comment by aawiseman** [comment]
@geobrando cool, any luck?

**Comment by geobrando** [comment]
@aawiseman Did not receive any response so closing
