### ISSUE TITLE
New Chapter for Ukraine

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#242]
__Summary__
Maptime name: __Katya1403__
Contact name: Katya
Date submitted: 2018-06-05 10:03:05

- [ ] Add GH admins to new team: 
- [ ] Add Location (Ukraine) to chapters.json and /chapters page.

__Additional tasks__
- [ ] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by almccon** [comment]
`Katya1403` is not a real chapter name, or is it a valid github username. Would need to be more specific about where in Ukraine this chapter is located, in any case. Suggest closing.
