### ISSUE TITLE
New Chapter for Salzburg, Austria

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#245]
__Summary__
Maptime name: __MaptimeSalzburg__
Contact name: Jakob Miksch
Date submitted: 2018-07-27 15:48:45

- [x] Add GH admins to new team: https://github.com/jakobmiksch/ and https://github.com/augustinh22
- [x] Add Location (Salzburg, Austria) to chapters.json and /chapters page.

__Additional tasks__
- [x] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by JakobMiksch** [comment]
Thanks for creating this issue. Just let me and @augustinh22  know if there is something we shall do. We already reserved a Twitter account: https://twitter.com/maptimeSalzburg

**Comment by emilyashley** [comment]
update: emailed Jakob and Hannah  Aug 24, 2018, 10:36 AM PDT

assigning self to follow up on this.

also, twitter convo [here](https://twitter.com/JakobMiksch/status/1029633621768982528)

**Comment by augustinh22** [comment]
Would it also be possible to get a maptime.io e-mail address for our chapter?

**Comment by JakobMiksch** [comment]
@emilyashley are there any updates about this issue?
we already had our first meetup and would like to post something on the website ...
thanks and best wishes!

**Comment by geobrando** [comment]
Hey @JakobMiksch  It looks like you a site and have had a meeting as recent as September 2021. Let us know if you are still active and if we can add your organizer info so it is listed here. 

https://maptime.io/chapters/

**Comment by augustinh22** [comment]
Hey @geobrando ! We are still around, though waiting a bit for nicer weather to avoid indoor meetings still.

**Comment by geobrando** [comment]
@augustinh22 Great. Let us know if you want us to add your organizers names and also a personal twitter link to that webpage. Right now it is blank

![image](https://user-images.githubusercontent.com/1833870/162755290-0d81d1ab-191e-44ed-951a-3063d46c4663.png)
