### ISSUE TITLE
New Chapter for Singapore

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#247]
__Summary__
Maptime name: __MaptimeSG__
Contact name: Jian He
Date submitted: 2018-08-13 10:52:53

- [ ] Add GH admins to new team: 
- [ ] Add Location (Singapore) to chapters.json and /chapters page.

__Additional tasks__
- [ ] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by emilyashley** [comment]
update: returned email to Jian He. 
Aug 24, 2018, 10:25 AM PDT

Assigning myself to follows this.

**Comment by philam** [comment]
Added to map: https://github.com/maptime/maptime.github.io/commit/1565cb316268801d1b81ff383d3383137093b742 #177

**Comment by geobrando** [comment]
Reached out to Jian to confirm if they are still active as their meetup account is no longer active and there have not been any tweets since 2019. If not we'll remove from chapters.json
