### ISSUE TITLE
New Chapter for up

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#249]
__Summary__
Maptime name: __maptimedc__
Contact name: kamal
Date submitted: 2018-10-09 11:15:55

- [ ] Add GH admins to new team: ajsjd
- [ ] Add Location (up) to chapters.json and /chapters page.

__Additional tasks__
- [ ] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by philam** [comment]
I assume that this is for Washington, DC?

**Comment by aawiseman** [comment]
This seems like not enough info

**Comment by briandaviddavidson** [comment]
If they are interested in running the DC chapter, we have all of this already spun up. I'm happy to connect with them on taking it over.
