### ISSUE TITLE
New Chapter for Maastricht

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#253]
__Summary__
Maptime name: __Maptime Maastricht__
Contact name: Sven Reulen
Date submitted: 2019-01-16 11:13:27

- [ ] Add GH admins to new team: 
- [ ] Add Location (Maastricht) to chapters.json and /chapters page.

__Additional tasks__
- [ ] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by philam** [comment]
Duplicate of #252
