### ISSUE TITLE
New Chapter for Tucson, Arizona, USA

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#257]
__Summary__
Maptime name: __MaptimeTUS__
Contact name: Kiri Carini
Date submitted: 2019-03-30 18:42:17

- [x] Add GH admins to new team: https://github.com/kcarini
- [x] Add Location (Tucson, Arizona, USA) to chapters.json and /chapters page.

__Additional tasks__
- [x] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by philam** [comment]
Hi @kcarini - do you have a Twitter account or website to add to the Chapters listing?

**Comment by kcarini** [comment]
Yes I have @MaptimeTUS but have not set up a website or GitHub yet. Still
working on that.

Thanks!

Kiri

**Comment by philam** [comment]
Thanks! Just post here when you've got them ready and I can add them to your listing on the Maptime website.

**Comment by philam** [comment]
Added to Chapters map with Twitter account.
