### ISSUE TITLE
New Chapter for Christchurch, New Zealand

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#258]
__Summary__
Maptime name: __MaptimeChristchurch__
Contact name: Andrew Douglas-Clifford
Date submitted: 2019-04-03 05:20:41

- [ ] Add GH admins to new team: Yes
- [ ] Add Location (Christchurch, New Zealand) to chapters.json and /chapters page.

__Additional tasks__
- [ ] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by philam** [comment]
Hi there! Would you be able to post your GitHub username please?

**Comment by geobrando** [comment]
Duplicate of #256
