### ISSUE TITLE
New Chapter for Port harcourt Nigeria

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#259]
__Summary__
Maptime name: __MaptimeZaph__
Contact name: My  name is Joseph from Nigeria, I am 22 years old.
Date submitted: 2019-04-11 19:58:03

- [ ] Add GH admins to new team: ok
- [ ] Add Location (Port harcourt Nigeria) to chapters.json and /chapters page.

__Additional tasks__
- [ ] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by philam** [comment]
Hi there! Would you be able to send us your GitHub username please?

**Comment by aawiseman** [comment]
I think we can close this one, no response since then
