### ISSUE TITLE
New Chapter for Worldwide

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#261]
__Summary__
Maptime name: __Donors__
Contact name: Donor
Date submitted: 2019-08-04 10:49:14

- [ ] Add GH admins to new team: No
- [ ] Add Location (Worldwide) to chapters.json and /chapters page.

__Additional tasks__
- [ ] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by aawiseman** [comment]
Just going through old ones, what kind of chapter is this? @geografa

**Comment by geografa** [comment]
eep. no idea. Also, not sure how this was made. The Typeform doesn't function anymore. I think there was a Zapier integration needing repair.

**Comment by aawiseman** [comment]
Gotcha. I will close then. We might also want to think of a better way to onboard chapters if anybody is interested
