### ISSUE TITLE
New Chapter for Duluth, Minnesota, USA

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#262]
__Summary__
Maptime name: __MaptimeDuluth__
Contact name: Zachary Vavra
Date submitted: 2019-09-13 11:01:51

- [ ] Add GH admins to new team: Zach Vavra's Github account "zvavra"
- [ ] Add Location (Duluth, Minnesota, USA) to chapters.json and /chapters page.

__Additional tasks__
- [ ] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by geobrando** [comment]
Duplicated by #237
