### ISSUE TITLE
New Chapter for Phoenix, Arizona, USA

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#265]
__Summary__
Maptime name: __MaptimePhoenix__
Contact name: Matthew Toro
Date submitted: 2019-11-14 20:12:27

- [ ] Add GH admins to new team: https://github.com/MTORO003
- [ ] Add Location (Phoenix, Arizona, USA) to chapters.json and /chapters page.

__Additional tasks__
- [ ] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by geobrando** [comment]
Hello @MTORO003. I see this request is over two years old but let us know if you're running a Phoenix chapter or are still interested in doing so.  I suspect you're not so I'm closing this but can reopen.
