### ISSUE TITLE
Where should we put onboarding resources?

### ISSUE THREAD

**Issue by lyzidiamond** [maptime/maptime-admin#42]
(Sorry about the first issue -- wrong spot!)

/cc @geografa @svmatthews @almccon @bethschechter

I want to make a page for onboarding resources. At first it's going to live in a gist (which I will link to in a comment here), but where should it live after that? Comments and thoughts more than welcome.

**Comment by bethschechter** [comment]
@lyzidiamond I've currently linked to it in the .readme for maptime-admin. 
We also need a Start a new Chapter page on .io. 
Chapter/start-a-chapter
and that could be a place where we (a) link to the onboarding docs and then (b) provide a form to fill out when people are ready. 
I know forms seem inhuman, but we need to move towards some kind of automation for this process. ...which is another issue...

**Comment by svmatthews** [comment]
Looking into forms on static sites @bethschechter and running into [Formspree](http://formspree.io/) which sends information to a remote DB and emails the results to a specified email. Seems like it would be perfect. Could have all of these run straight into `hello@maptime.io`

**Comment by svmatthews** [comment]
> Yep, for now we cap submissions to 1000 per email for each month. If you need more, please reach out to team@formspree.io.

**Comment by bethschechter** [comment]
@svmatthews cool! 1000 a month is totally enough.

**Comment by svmatthews** [comment]
Also, this is starting to get pretty similar to #48 - mind if I mark as duplicate?

**Comment by geografa** [comment]
yes plz :)

**Comment by bethschechter** [comment]
thanks! I don't know how to merge things.

**Comment by svmatthews** [comment]
Don't have permissions to, but it's closed and referenced so whatevs! ¯\_(ツ)_/¯

**Comment by geografa** [comment]
ooh. I think I need a better profile image. Every time I close a ticket it looks like I'm being such jerk about it.

**Comment by svmatthews** [comment]
"The Enforcer"
