### ISSUE TITLE
add maptime detroit repo

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#47]
add users:

- Dexter Slusarski (dexter@makeloveland.com)
- Diana Flora (diana@datadrivendetroit.org)
- Jimmy McBroom (james.mcbroom@gmail.com)

**Comment by jmcbroom** [comment]
hey, we are also on github at : maptimedet and site is : maptimedet.github.io

thanks@

**Comment by geografa** [comment]
All set. https://github.com/maptime/detroit
Can you send over github usernames and I'll add to the admins?

**Comment by geobrando** [comment]
Hey @jmcbroom : Looks like you guys are set up at http://maptimedet.github.io.

Have any need for https://github.com/maptime/detroit for any reason and are there any admins you want us to add?

**Comment by geobrando** [comment]
OK.  Added several organizers to Slack and to the Github org.  Created an admin team in case you wanted to use maptime/detroit and host a site at maptime.io/detroit.
