### ISSUE TITLE
Better Design Onboarding Process

### ISSUE THREAD

**Issue by bethschechter** [maptime/maptime-admin#48]
@geografa @lyzidiamond @almccon @camilleanne 

We need to decide
* where does this Start a Chapter page live?
* what parts are automated?

My thought is to have this completely automated (save adding people to respective Slack/GH/etc), and hello@maptime.io for questions. Does that work? How can we make this simple and human w/o someone writing repetitive emails?

**Comment by svmatthews** [comment]
OMG Formspree is the **coolest!**

**Comment by geobrando** [comment]
@bethschechter Just found the [wiki page](https://github.com/maptime/maptime-admin/wiki/Onboarding-Checklist) that you created. Since I assume you're the keeper of the stickers should I just alert you when a new chapter has joined and needs stickers?  What about the email lists, MaptimeHQ twitter items, and @maptime.io email addresses?

**Comment by svmatthews** [comment]
Sticker delivery method is questionable ... :wink: https://twitter.com/MaptimeHQ/status/595718236483809280

**Comment by almccon** [comment]
Hah, @svmatthews! Definitely a blocker!

**Comment by almccon** [comment]
I dunno if the onboarding docs are the appropriate place for this, but we should also encourage chapters to be more autonomous regarding stickers. Serious bonus points for local fundraising and local designs like MaptimeBER. https://instagram.com/p/y-J0izjdkp/

**Comment by bethschechter** [comment]
Yes! Please do for now. I am trying to find a better sticker
solution...like putting them on Zazzle for people to order. For now, yes!
Please let me know and i'm happy to put them in the mail. I already have
replacements out to DC and Seattle :)

On Thu, May 7, 2015 at 1:13 PM, Alan McConchie <notifications@github.com>
wrote:

> Hah, @svmatthews <https://github.com/svmatthews>! Definitely a blocker!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maptime/maptime-admin/issues/48#issuecomment-100003848>
> .
>



-- 
@bethschechter
Maptime <http://maptime.io/> founder
ATL –> SF –> PDX

**Comment by bethschechter** [comment]
Totally. Doing that is a bit of a shift in how we've been doing things, so
I want to communicate about that appropriately. I don't want people to
think that HQ doesn't care...we do, which is why we want people to sustain
themselves!

On Thu, May 7, 2015 at 1:15 PM, Alan McConchie <notifications@github.com>
wrote:

> I dunno if the onboarding docs are the appropriate place for this, but we
> should also encourage chapters to be more autonomous regarding stickers.
> Serious bonus points for local fundraising and local designs like
> MaptimeBER. https://instagram.com/p/y-J0izjdkp/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maptime/maptime-admin/issues/48#issuecomment-100004485>
> .
>



-- 
@bethschechter
Maptime <http://maptime.io/> founder
ATL –> SF –> PDX

**Comment by geobrando** [comment]
I assume it'll be made clear at some point what HQ will support and what chapters are on their own for, and how finances will be handled generally.  But a zazzle store is a great idea either way should chapters have funding to support buying merch.

@bethschechter What should I do about the other onboarding items?

**Comment by bethschechter** [comment]
@geobrando which other items? Like stickers and things?

**Comment by geobrando** [comment]
@bethschechter I guess the only other items from your onboarding list is stuff related to the HQ twitter account and approving mailing list requests.  I can just ping on of you at HQ for the twitter items and then instruct people to join the two email lists and one of you can approve.

Oh, there's also asking them if they want an @maptime.io email address.  Should I direct them to @lyzidiamond?  Trying to reduce this to as few steps as possible.

**Comment by bethschechter** [comment]
Right! Thanks, those things.

Twitter and mailing list - both need someone to keep their eyes on it.
@almccon does it, as do I and @lyzidiamond, but if there was someone who
just monitored those things + followed new chapters, that would be amazing.
I'm reminded that we need to find a good system for tracking volunteer
needs - wiki? issues? I'm up for whatever and need recommendations for what
works best given this workflow.

@maptime.io mailing addresses may stay or go, as they are just forwarding
addresses. The same thing applies as above: what do you guys recommend as
being the easiest/most efficient way to get that done?



On Fri, May 8, 2015 at 1:08 PM, Brandon Knight <notifications@github.com>
wrote:

> @bethschechter <https://github.com/bethschechter> I guess the only other
> items from your onboarding list is stuff related to the HQ twitter account
> and approving mailing list requests. I can just ping on of you at HQ for
> the twitter items and then instruct people to join the two email lists and
> one of you can approve.
>
> Oh, there's also asking them if they want an @maptime.io email address.
> Should I direct them to @lyzidiamond <https://github.com/lyzidiamond>?
> Trying to reduce this to as few steps as possible.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maptime/maptime-admin/issues/48#issuecomment-100344446>
> .
>



-- 
@bethschechter
Maptime <http://maptime.io/> founder
ATL –> SF –> PDX

**Comment by geobrando** [comment]
Progress has been made in improving the onboarding process with 

* The redesign of http://maptime.io/start which populates github issues and the chapter list google sheet
* A dedicated team for onboarding new chapters
* The [onboarding checklist](https://github.com/maptime/maptime-admin/wiki/Onboarding-Checklist)

There is always room for improvement and suggestions are welcome from all by opening up new issues here or in the maptime.github.io repo when appropriate.

Other topics here are more chapter maintenance issues than onboarding ones and could also be addressed individually.
