### ISSUE TITLE
New Chapter for NE Portland

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#69]
__Summary__

- [x] Contact name: Hugo
- [x] Maptime Twitter account: [](https://twitter.com//)
- [x] GH admins: hugo
- [x] Location: NE Portland
- [x] Date submitted: 2015-04-26 16:52:57

__Additional tasks__
- [x] Add to Slack
- [x] Add to chapters map

/cc @maptime/admin-onboarders

**Comment by bethschechter** [comment]
Coool! That will be my hood! Yes!

//typed with thumbs
