### ISSUE TITLE
Maptime Onboarding Script

### ISSUE THREAD

**Issue by geobrando** [maptime/maptime-admin#70]
@maptime/owners:

Many moons ago in maptime/starter#2 I told @geografa I was working on a script that might be of some value in the onboarding process.  Here's what I threw together.

https://gist.github.com/geobrando/c5686132f90de8ca6867

The script:

1. Prompts user for the chapter name and the name of one admin for the new chapter
1. Creates a new repo for that chapter
1. Clones the starter repo and push it to the new chapter repo as a 'gh-pages' branch
1. Creates a new team to admin the chapter repo
1. Adds the user to the admin team for the new repo.  If they're not already a member of the Maptime org, it should send them an invite.  @geografa: Can you confirm that you received a test email?

Tried to write it in pure bash but Github does a weird thing and only lets you refer to a team by a "Team ID" so I had to use [jq](http://stedolan.github.io/jq/download/) to parse the json reponse in Step 4 to get the id to use in Step 5.

This is pretty hack.  No error handling but it's something I plan use for onboarding.  It also requires the onboarder generate an access token and save it as an environment variable.  But that was the best way to let those with two-factor authorization use it.

**Comment by geografa** [comment]
@geobrando Awesome. I'll have to give this a go. I didn't receive the email.

**Comment by geobrando** [comment]
@geografa Thanks. Yeah.  Received a "Not found" response in that request since you weren't in my sandbox org but realize I should get a "Pending" if they sent you an email to join.  Have to figure out what's going on there.  The rest of this works though.

**Comment by geografa** [comment]
Got it!
![squaid](https://cloud.githubusercontent.com/assets/134753/7340820/aa0e197a-ec4a-11e4-8019-e162439b1eca.png)

**Comment by bethschechter** [comment]
<3

On Sun, Apr 26, 2015 at 7:30 PM, geografa <notifications@github.com> wrote:

> Got it!
> [image: squaid]
> <https://cloud.githubusercontent.com/assets/134753/7340820/aa0e197a-ec4a-11e4-8019-e162439b1eca.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maptime/maptime-admin/issues/70#issuecomment-96476693>
> .
>



-- 
@bethschechter
Maptime <http://maptime.io/> founder
ATL –> SF –> PDX

**Comment by geografa** [comment]
@geobrando  I want to add a variable for the team country, state/province. I added a input for `city` but I'm screwing something up on line 28: 

`-d "{\"name\":\"${chapter}-admin\",\"permission\":\"write\",\"repo_names\":[\"maptime/${chapter}\"]}" \`

any ideas?

**Comment by geobrando** [comment]
@geografa Adding it in #75.  Let's develop that here so we're using the same version

What kind of error are you getting?

**Comment by geografa** [comment]
It was a message not found so I'm guessing it wasn't parsing the result correctly.

I'm making you a member of onboarder team so you can write to this repo if that's ok.

**Comment by geografa** [comment]
NM - looks like you already are. Too early here.

**Comment by geobrando** [comment]
Great. Closing this. Let's take to Slack or we can open new tickets for specific improvements.
