### ISSUE TITLE
New Chapter for Richmond Upon Thames, London, UK

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#72]
__Summary__

Contact name: John Wilson
Date submitted: 2015-04-27 20:23:40

- [x] Add Maptime Twitter account: [](https://twitter.com//)
- [x] Add GH admins: gisyohn antmole
- [ ] Add Location to chapters.json and /chapters page: Richmond Upon Thames, London, UK

__Additional tasks__
- [x] Add to Slack

/cc @maptime/admin-onboarders

**Comment by geografa** [comment]
@gisyohn @antmole repo is made and you both have been added to the team. Next up is the chapters map and editing your posts and events.

**Comment by antmole** [comment]
cool! thanks

**Comment by geobrando** [comment]
Hi @gisyohn and @antmole 

I'm confused.  It looks like we've had a Maptime in West London for some time.
https://twitter.com/maptimewlon
https://www.eventbrite.co.uk/e/maptime-west-london-tickets-16960011852

Are you affiliated with this chapter or is this a new request?

**Comment by antmole** [comment]
Hi Brandon,

I can confirm that we are both affiliated to maptime west London.

Regards

Billy

**Comment by geobrando** [comment]
@antmole Great! Let's get you added to the map and that chapters list.

Want to add yourself to [chapters.json](https://github.com/maptime/maptime.github.io/blob/master/_data/chapters.json?short_path=7491cf6)?

If you prefer, you can just reply with all your information and I can commit the changes.  I think I know most of it but want to be sure.

**Comment by geobrando** [comment]
Added to chapters.json in maptime/maptime.github.io#200
