### ISSUE TITLE
New Chapter for Turku, Finland

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#76]
__Summary__

Contact name: Sanna Jokela
Date submitted: 2015-04-30 10:50:41

- [x] Add Maptime Twitter account: [](https://twitter.com//)
- [x] Add GH admins: skmuju
- [x] Add Location to chapters.json and /chapters page: Turku, Finland

__Additional tasks__
- [x] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by skmuju** [comment]
MaptimeTurku twitter account ready https://twitter.com/MaptimeTurku , and I'm on slack allready :)

**Comment by geografa** [comment]
@skmuju your repo is up: http://maptime.io/turku/
