### ISSUE TITLE
New Chapter for New Orleans, Louisiana, USA

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#78]
__Summary__

Contact name: Emily Ashley
Date submitted: 2015-05-06 19:52:10

- [x] Add Maptime Twitter account: [](https://twitter.com//)
- [ ] Add GH admins: US90
- [x] Add Location to chapters.json and /chapters page: New Orleans, Louisiana, USA

__Additional tasks__
- [x] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by geobrando** [comment]
Hi @US90. 

Created a repo for your website using our template.  You can find the repo [here](https://github.com/maptime/nola) and your site is served [here](http://maptime.io/nola/). You're not obligated to use it though.  It's a Jekyll site. Feel free to create a site from scratch if you're more comfortable with that or we can disable if you prefer not to maintain one at all.  I can guide you on how to customize and how to add posts once you start planning events if you need the help. Let me know if you're not comfortable using github/git and I can help you there as well.  Once you join the Maptime github organization you'll have full access to your chapter repo.

We'll add you to [this file](https://github.com/maptime/maptime.github.io/blob/master/_data/chapters.json?short_path=3d3d80f) to get you on our map and in our list of chapters.  We'll mark it as "coming soon" until you're ready to start holding events. Let me know if you have any of the following, or feel free to submit a pull request with the changes:

* Twitter account for your chapter
* Your personal twitter account
* A meetup.com page (or any other meetup-like page)
* Any additional organizers' info

Thanks!

**Comment by geobrando** [comment]
Org invite pending for @US90.  Closing.

**Comment by emilyashley** [comment]
Can we switch the github admin in New Orleans over to @emilyashley? Please and thank you!

**Comment by geobrando** [comment]
:+1:
