### ISSUE TITLE
New Chapter for Ahmedabad, Gujarat, India

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#81]
__Summary__

Contact name: Shravan Shah
Date submitted: 2015-05-07 17:51:51

- [x] Add Maptime Twitter account: [](https://twitter.com//)
- [x] Add GH admins: shravan91
- [x] Add Location to chapters.json and /chapters page: Ahmedabad, Gujarat, India

__Additional tasks__
- [x] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by geografa** [comment]
Hi @shravan91!

Created a repo for your website using our template. You can find the repo [here](https://github.com/maptime/ahmedabad) and your site is served [here](https://maptime.io/ahmedabad). You're not obligated to use it though. It's a [Jekyll](http://jekyllrb.com/) site. Feel free to create a site from scratch if you're more comfortable with that or we can disable if you prefer not to maintain one at all. I can guide you on how to customize and how to add posts once you start planning events if you need the help. Let me know if you're not comfortable using github/git and I can help you there as well. 

You'll need to add your chapter to [this file](https://github.com/maptime/maptime.github.io/blob/master/_data/chapters.json?short_path=3d3d80f) to get you on our map and in our list of chapters. We'll mark it as "coming soon" until you're ready to start holding events. Let me know if that works out for you and if you have questions.

**Comment by geografa** [comment]
all good here.

**Comment by shravan91** [comment]
> - [x] Add to Slack

@geografa - How do I get onto Maptime Slack!

**Comment by geobrando** [comment]
@shravan91 Sending an invite to your Mapbox email.
