### ISSUE TITLE
New Chapter for Buffalo, New York, USA

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#83]
__Summary__
Maptime name: __MaptimeBuffalo__
Contact name: Lizzi Slivinski
Date submitted: 2015-05-08 23:35:58

- [x] Add Maptime Twitter account: [](https://twitter.com//)
- [x] Add GH admins: @eslivinski
- [x] Add Location to chapters.json and /chapters page: Buffalo, New York, USA

__Additional tasks__
- [x] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by geobrando** [comment]
Hi @eslivinski:

* Sent you an invitation to join our Slack and to join the Maptime github org.

* I created a repo with our webpage starter template which you find [here](https://github.com/maptime/buffalo).  This creates a page which is served [here](http://maptime.io/buffalo/).  You don't have to do anything with that now but if you're comfortable using git/github you can try adding a banner image where the blue is now and can eventually add events or blog entries if so desired.  Feel free to create a page from scratch as well. Check out some of the existing chapter pages for inspiration.

* Your chapter is also now visible on the map in in the list at http://maptime.io/chapters/

Feel free to address any questions you have about Maptime or how to get started in our Slack.  You can ping me (brandon) in the #general channel or send me a Direct Message.

Thanks!
