### ISSUE TITLE
New Chapter for Memphis, TN, USA

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#84]
__Summary__
Maptime name: __MaptimeMAGIC__
Contact name: Tom Lawrence
Date submitted: 2015-05-13 20:45:22

- [ ] Add Maptime Twitter account: [](https://twitter.com//)
- [x] Add GH admins: 
- [x] Add Location to chapters.json and /chapters page: Memphis, TN, USA

__Additional tasks__
- [x] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by geobrando** [comment]
Should email to get more information about meaning of "MaptimeMAGIC".

@lyzidiamond : Were you ever able to reach the Memphis person you met at FOSS4G?

**Comment by lyzidiamond** [comment]
@geobrando no, nothing happened there.

In terms of MAGIC, it stands for "Mid-America GIS Consortium, Ltd." per http://www.urisa.org/main/chapters/

**Comment by geobrando** [comment]
@lyzidiamond Hmm... Are we OK with that?

**Comment by almccon** [comment]
Two things: 

That name sure doesn't sound newbie-friendly... Most people in the region won't know what it means, and when they find out what the acronym is, they will be deterred. "GIS" is scary, and so is "consortium".

Second, it looks like MAGIC has a very wide geographic scope... they've done events as far away as Kansas City and Sioux Falls. Surely a chapter based in Memphis can't claim to represent potential Maptime communities in those areas.

**Comment by geobrando** [comment]
I had similar thoughts, Alan. Emailing Tom now.

**Comment by lyzidiamond** [comment]
MaptimeMEM FTW

**Comment by tlawrence28** [comment]
This is Tom.  I have been out of town and unable to respond until now.  Our area of coverage is West TN, North MS and Eastern AR, basically centered on Memphis.  We use the name MAGIC, so as to keep the groups from sounding like it is limited to the city.  There is also the term "Mid-South" that we use, but I think that other areas through the South use that term.  I am open to suggestions.  I noticed that most of the other groups tend to use the large city that is the center, so we can also do that with the name MaptimeMemphis.  I do see from the discussion that other GIS groups may also be using the MAGIC name, so that would not be good for our group.

**Comment by tlawrence28** [comment]
FYI - MAGIC in our case stands for Memphis Area Geographic Information Council.

**Comment by geografa** [comment]
@tlawrence28 I can appreciate how awesome it is when a acronym just works out for a group ;) . For the benefit of global users and being able to recognize cities at a glance, are you amenable to going with a geographically recognizable name? I realize there is no standard at the moment so this may be the precedent where we come up with this. I would suggest going with MaptimeMemphis or MaptimeMEM or whatever is your airport. Reason being is that you may encounter down the road that other cities in the MAGIC region start their own maptimes and MAGIC will be less relevant. That's just my suggestion.

**Comment by tlawrence28** [comment]
Sure.  We can change it to MaptimeMemphis or MaptimeMEM.

**Comment by tlawrence28** [comment]
I looked through the existing chapter names and changed ours to MaptimeMEM.  Can you check to make sure I did it correctly or would it be better just to start a new account with the MaptimeMEM name?

**Comment by tlawrence28** [comment]
MaptimeMEM has not shown up on the website.  Can anyone let me know what I need to do next to get our group up and running?

**Comment by geobrando** [comment]
@tlawrence28 This will be taken care of really soon. Many of us have been busy the past weekend with the State of the Map conference and our first Maptime summit in NYC on Monday.

I'll take ownership of this request and make sure you get added.

**Comment by tlawrence28** [comment]
No problem.  I just wanted to make sure it wasn't waiting on me.

**Comment by geobrando** [comment]
Hi @tlawrence28. You're now on the chapters page.  Let me know if you decide to get a MaptimeMEM twitter account or a meetup.com  page and we can add those as well.

Your website is served at http://maptime.io/memphis.  If you would like to maintain this site for MaptimeMEM, this can be managed by making changes to the repo at https://github.com/maptime/memphis.  There you'll find instructions for adding blog entries or events.  If you need help, don't hesitate to reach out to us on Slack.  My username is `@brandon` there.
