### ISSUE TITLE
New Chapter for NY

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#89]
__Summary__
Maptime name: __MaptimeNY__
Contact name: butros
Date submitted: 2015-05-15 01:20:27

- [ ] Add GH admins to new team: butros
- [ ] Add Location (NY) to chapters.json and /chapters page.

__Additional tasks__
- [ ] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by geobrando** [comment]
@geografa This one of your tests?

**Comment by geografa** [comment]
yes. zoops. thanks
