### ISSUE TITLE
New Chapter for "><img src=x onerror=prompt(111);>

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#94]
__Summary__
Maptime name: __typeform.com __
Contact name: "><img src=x onerror=prompt(111);>
Date submitted: 2015-05-20 11:09:02

- [ ] Add GH admins to new team: typeform.com 
- [ ] Add Location ("><img src=x onerror=prompt(111);>) to chapters.json and /chapters page.

__Additional tasks__
- [ ] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by geografa** [comment]
?

**Comment by geobrando** [comment]
Weird
