### ISSUE TITLE
New Chapter for Lagos, Nigeria

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#98]
__Summary__
Maptime name: __MaptimeLagos__
Contact name: Ayo Akinseye
Date submitted: 2015-05-30 11:37:33

- [x] Add GH admins to new team: 
- [x] Add Location (Lagos, Nigeria) to chapters.json and /chapters page.

__Additional tasks__
- [x] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by lyzidiamond** [comment]
!! :+1:

**Comment by geografa** [comment]
Hi Ayo! Can you please [setup a Github account](https://github.com/) so we can get your repository up and running? I'll follow up on email as well.

**Comment by mapnigeria** [comment]
Hi, I have set up a github account. Let me know the next steps

**Comment by geografa** [comment]
Invite sent. Repo added: https://github.com/maptime/lagos 

Now, it's a matter of editing your posts and events: http://maptime.io/lagos/

**Comment by geografa** [comment]
Sorry, sent that in a hurry ;) Here are some more explicit instructions:

- Your website is here: http://maptime.io/lagos/
- You can manage it, including customizing and adding posts and events using this repo, which you have push privileges to: https://github.com/maptime/lagos/.  If you'd rather not use the template and want to create a site from scratch, you're welcome to.
- Added your chapter to chapters.json, which renders your chapter in the list on on the map at http://maptime.io/chapters/. When you're ready to start having event we can remove the `"comingSoon": true` tag
- I would recommend grabbing "MaptimeLagos" on twitter, after which you'd add it to chapters.json as well as the _config.yml in your repo
-  Let us know if you think you'll have any need for a lagos@maptime.io email address.

Let me know if you have any questions either here or on Slack (`@geografa`)

**Comment by almccon** [comment]
@mapnigeria if you create a twitter account (perhaps @MaptimeLagos) by tomorrow, we can include you in a Friday welcome tweet!
