### ISSUE TITLE
New Chapter for Taipei, Taiwan

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#99]
__Summary__
Maptime name: __MaptimeTPE__
Contact name: Brandon Liu
Date submitted: 2015-06-01 07:07:03

- [x] Add GH admins to new team: bdon
- [x] Add Location (Taipei, Taiwan) to chapters.json and /chapters page.

__Additional tasks__
- [x] Add to Slack
- [x] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by geobrando** [comment]
Hey @bdon,

You should be good to go. 

* Your website is here: http://maptime.io/taipei/
* You can manage it, including customizing and adding posts and events using this repo, which you have push privileges to: https://github.com/maptime/taipei/.  If you'd rather not use the template and want to create a site from scratch, you're welcome to.
* Added your chapter to [chapters.json](https://github.com/maptime/maptime.github.io/blob/master/_data/chapters.json?short_path=06f67c1), which renders your chapter in the list on on the map at http://maptime.io/chapters/. When you're ready to start having event we can remove the `"comingSoon": true` tag
* I would recommend grabbing "MaptimeTPE" on twitter, after which you'd add it to chapters.json as well as the _config.yml in your repo
* Let us know if you think you'll have any need for a taipei@maptime.io email address.

Let me know if you have any questions either here or on Slack (`@brandon`)

**Comment by almccon** [comment]
@bdon, if you create a twitter account by tomorrow, we can include you in a #FF welcome tweet!

**Comment by bdon** [comment]
@almccon https://twitter.com/MaptimeTPE

**Comment by almccon** [comment]
:+1:
